"""The selenium test."""
# pylint: skip-file

# Generated by Selenium IDE
import json  # pylint: disable=import-error disable=unused-import
import time  # pylint: disable=import-error disable=unused-import
import pytest  # pylint: disable=import-error disable=unused-import
from selenium import webdriver  # pylint: disable=import-error
from selenium.webdriver.chrome.options import Options  # pylint: disable=import-error
from selenium.webdriver.common.by import By  # pylint: disable=import-error
from selenium.webdriver.common.action_chains import ActionChains  # pylint: disable=import-error disable=unused-import
from selenium.webdriver.support import expected_conditions  # pylint: disable=import-error disable=unused-import
from selenium.webdriver.support.wait import WebDriverWait  # pylint: disable=import-error disable=unused-import
from selenium.webdriver.common.keys import Keys  # pylint: disable=import-error disable=unused-import
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities  # pylint: disable=import-error disable=unused-import
from selenium.webdriver.support import expected_conditions as EC


class TestCockroachdbtest1():
    """CockroachDB web ui testing"""

    def setup_method(self, method):  # pylint: disable=unused-argument
        """setup method."""
        chrome_options = Options()
        chrome_options.add_argument("--headless")
        chrome_options.add_argument('--disable-dev-shm-usage')
        chrome_options.add_argument("disable-infobars")
        chrome_options.add_argument("--disable-extensions")
        chrome_options.add_argument("--disable-gpu")
        chrome_options.add_argument("--no-sandbox")
        self.driver = webdriver.Chrome(
            options=chrome_options)  # pylint: disable=attribute-defined-outside-init
        self.driver.implicitly_wait(10)

    def teardown_method(self, method):  # pylint: disable=unused-argument
        """teardown method."""
        self.driver.quit()

    def test_login(self, params):
        self.driver.get(
                "http://{}:{}/".format(
                    params["server"],
                    params["port"]))  # pylint: disable=consider-using-f-string
        self.driver.set_window_size(1366, 732)
        self.driver.find_element(By.NAME, "username").click()
        self.driver.find_element(By.NAME, "username").send_keys("rfuname")
        self.driver.find_element(By.NAME, "password").click()
        self.driver.find_element(By.NAME, "password").send_keys("password")
        self.driver.find_element(By.CSS_SELECTOR, ".crl-button--type-primary--xITEm .crl-button__content--A8AxK").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ant-table-row:nth-child(1) .text--body").click()
        self.driver.find_element(By.LINK_TEXT, "View Logs").click()
        self.driver.find_element(By.LINK_TEXT, "Metrics").click()
        self.driver.find_element(By.LINK_TEXT, "Databases").click()
        self.driver.find_element(By.LINK_TEXT, "defaultdb").click()
        self.driver.find_element(By.LINK_TEXT, "\"public\".\"users\"").click()
        self.driver.find_element(By.LINK_TEXT, "users_pkey").click()
        self.driver.find_element(By.LINK_TEXT, "Table: \"public\".\"users\"").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ant-tabs-tab:nth-child(2)").click()
        self.driver.find_element(By.LINK_TEXT, "SQL Activity").click()
        self.driver.find_element(By.CSS_SELECTOR, ".layout-panel__body").click()
        self.driver.find_element(By.CSS_SELECTOR, ".margin-top-btn--rZt79").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ant-tabs-tab:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ant-tabs-tab:nth-child(3)").click()
        self.driver.find_element(By.LINK_TEXT, "Insights").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ant-tabs-tab:nth-child(2)").click()
        self.driver.find_element(By.LINK_TEXT, "Network").click()
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.find_element(By.LINK_TEXT, "Hot Ranges").click()
        self.driver.find_element(By.CSS_SELECTOR, ".side-navigation__navigation-item:nth-child(8)").click()
        self.driver.find_element(By.LINK_TEXT, "Jobs").click()
        self.driver.find_element(By.CSS_SELECTOR, ".row-wrapper__row--2rAs0:nth-child(7) .jobs-table__cell--description--1xIOi").click()
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.find_element(By.CSS_SELECTOR, ".ant-tabs-tab:nth-child(2)").click()
        self.driver.find_element(By.LINK_TEXT, "Schedules").click()
        self.driver.find_element(By.LINK_TEXT, "Advanced Debug").click()
      
