version: '3'

services:
  yq:
    image: ${YQ_IMAGE_REPOSITORY}:${YQ_IMAGE_TAG}
    volumes:
      - ./tests:/tmp
    cap_add:
      - SYS_PTRACE 
    entrypoint: sh
    stdin_open: true
    tty: true
