version: '3'

services:
  terragrunt:
    image: ${TERRAGRUNT_IMAGE_REPOSITORY}:${TERRAGRUNT_IMAGE_TAG}
    volumes:
      - ./test/main.tf:/home/terraform/main.tf  
      - ./test/terragrunt.hcl:/data/terragrunt.hcl
      - ./commands.sh:/tmp/commands.sh
    ports:
      - "4000:4000"
    cap_add:
      - SYS_PTRACE
    entrypoint:
      - "sleep"
    tty: true
    stdin_open: true
    command:
      - "infinity"
