version: '2'

services:
  kaniko:
    image: ${KANIKO_IMAGE_REPOSITORY}:${KANIKO_IMAGE_TAG}
    cap_add:
      - SYS_PTRACE
    entrypoint:
      - "sleep"
    command:
      - "infinity"
    volumes:
      - ./kaniko_context/:/workspace/
    

  registry: 
    image: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-container-registry:latest
    user: root
    ports:
      - '5001:5000'
    volumes:
      - ./registry_config.yml:/etc/docker/registry/config.yml
      - /registry:/var/lib/registry

