version: '3'
services:
  zeek:
    image: registry1.dso.mil/ironbank/opensource/zeek/zeek:6.0.4
    # image: ${ZEEK_IMAGE_REPOSITORY}:${ZEEK_IMAGE_TAG}
    network_mode: host
    user: root
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
      - NET_RAW
    volumes:
      - ./hello.zeek:/tmp/hello.zeek
      - ./start_zeek.sh:/usr/local/bin/start_zeek.sh
      - ./commands.sh:/tmp/commands.sh
    entrypoint: ["/bin/sh", "-c"]
    command: ["/usr/local/bin/start_zeek.sh"]