version: '2.1'

services:
  mysql-master:
    image: ${MYSQL_IMAGE_REPOSITORY}:${MYSQL_IMAGE_TAG}
    ports:
      - '3306'
    volumes:
      - 'mysql_master_data:/bitnami/mysql/data'
    environment:
      - RF_VERBOSE=1
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_USER=my_user
      - MYSQL_DATABASE=my_database
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=my_root_password
      - RF_ACCESS_TOKEN=${RF_ACCESS_TOKEN}
    cap_add:
      - SYS_PTRACE
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  mysql-slave:
    image: ${MYSQL_IMAGE_REPOSITORY}:${MYSQL_IMAGE_TAG}
    ports:
      - '3306'
    depends_on:
      - mysql-master
    environment:
      - RF_VERBOSE=1
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_USER=my_user
      - MYSQL_DATABASE=my_database
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=my_root_password
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - RF_ACCESS_TOKEN=${RF_ACCESS_TOKEN}
    cap_add:
      - SYS_PTRACE
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  mysql_master_data:
    driver: local
