version: '2'

services:
  alertmanager:
    image: ${ALERTMANAGER_IMAGE_REPOSITORY}:${ALERTMANAGER_IMAGE_TAG}
    cap_add:
      - SYS_PTRACE
    ports:
      - "9093:9093"
    volumes:
      - alertmanager-data:/data
volumes:
  alertmanager-data:
