name: alertmanager-ib
official_name: Alertmanager Ironbank
official_website: https://prometheus.io/
source_image_provider: Platform One
source_image_repo: registry1.dso.mil/ironbank/opensource/prometheus/alertmanager
source_image_repo_link: https://registry1.dso.mil/harbor/projects/3/repositories/opensource%2Fprometheus%2Falertmanager
source_image_readme: https://repo1.dso.mil/dsop/opensource/prometheus/alertmanager/-/blob/development/README.md
rf_docker_link: rapidfort/alertmanager-ib
image_workflow_name: alertmanager_ironbank
github_location: alertmanager/ironbank
report_url: https://us01.rapidfort.com/app/community/imageinfo/registry1.dso.mil%2Fironbank%2Fopensource%2Fprometheus%2Falertmanager
usage_instructions: |
  $ docker run --name alertmanager -d -p 9093:9093 rapidfort/alertmanager-ib
what_is_text: "The Alertmanager handles alerts sent by client applications such as the Prometheus server. \n"
disclaimer: |
  Trademarks: This software listing is packaged by RapidFort. The respective trademarks mentioned in the offering are owned by the respective companies, and use of them does not imply any affiliation or endorsement.
is_locked: "False"
input_registry:
  registry: registry1.dso.mil
  account: ironbank
repo_sets:
  - opensource/prometheus/alertmanager:
      input_base_tag: "v0.27."
      output_repo: alertmanager-ib
runtimes:
  - type: docker_compose
    script: dc_coverage.sh
    compose_file: docker-compose.yml
    image_keys:
      alertmanager-ib:
        repository: "ALERTMANAGER_IMAGE_REPOSITORY"
        tag: "ALERTMANAGER_IMAGE_TAG"
