# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestAirflowci1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_airflowci1(self):
        self.driver.get(
            "http://172.31.36.230:3004/login/?next=http%3A%2F%2F172.31.36.230%3A3004%2Fhome")
        self.driver.set_window_size(1440, 790)
        self.driver.find_element(By.ID, "username").send_keys("rf-test")
        self.driver.find_element(By.ID, "password").send_keys("rf_")
        self.driver.find_element(By.ID, "password").send_keys("rf_password")
        self.driver.find_element(
            By.ID, "password").send_keys("rf_password123!")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(1) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(2) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(3) .switch").click()
        self.driver.execute_script("window.scrollTo(0,85)")
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(4) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(5) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(6) .switch").click()
        self.driver.execute_script("window.scrollTo(0,132)")
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(7) .switch").click()
        self.driver.execute_script("window.scrollTo(0,196)")
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(8) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(9) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(10) .switch").click()
        self.driver.execute_script("window.scrollTo(0,260)")
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(11) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(12) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(13) .switch").click()
        self.driver.execute_script("window.scrollTo(0,393)")
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(14) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(15) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(16) .switch").click()
        self.driver.execute_script("window.scrollTo(0,912)")
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(17) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(18) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(19) .switch").click()
        self.driver.execute_script("window.scrollTo(0,1017)")
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(20) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(21) .switch-label").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(22) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(23) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(24) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(25) .switch").click()
        self.driver.execute_script("window.scrollTo(0,1294.5)")
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(26) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(27) .switch").click()
        self.driver.find_element(By.LINK_TEXT, "›").click()
        self.driver.find_element(By.LINK_TEXT, "»").click()
        element = self.driver.find_element(By.LINK_TEXT, "Active 0")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.LINK_TEXT, "Active 0").click()
        self.driver.find_element(By.LINK_TEXT, "Paused 0").click()
        self.driver.find_element(By.LINK_TEXT, "DAGs").click()
        self.driver.find_element(By.LINK_TEXT, "DAG Runs").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(4)").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(1) .label").click()
        self.driver.find_element(By.LINK_TEXT, "latest_only").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "#latest_only > .label-container").click()
        self.driver.find_element(By.CSS_SELECTOR, ".close > span").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "#task1 > .label-container").click()
        self.driver.find_element(By.CSS_SELECTOR, ".close > span").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".nav-pills > li:nth-child(3) > a").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".nav-pills > li:nth-child(4) > a").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".nav-pills > li:nth-child(5) > a").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".nav > li:nth-child(6) > a").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".nav > li:nth-child(7) > a").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".nav > li:nth-child(8) > a").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "li:nth-child(9) > a").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "li:nth-child(10) > a").click()
        self.driver.find_element(By.LINK_TEXT, "Next").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".nav-pills > li:nth-child(1) > a").click()
        self.driver.find_element(By.ID, "root").click()
        self.driver.find_element(By.ID, "root").click()
        self.driver.find_element(By.ID, "root").click()
        self.driver.find_element(By.ID, "root").click()
        self.driver.find_element(By.ID, "root").click()
        self.driver.find_element(By.ID, "root").click()
        self.driver.find_element(By.LINK_TEXT, "Jobs").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(51) .label").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(51) > td:nth-child(2)").click()
        self.driver.find_element(By.LINK_TEXT, "Audit Logs").click()
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(68) a").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "#also_run_this > .label-container").click()
        self.driver.find_element(By.ID, "btn_log").click()
        self.driver.execute_script("window.scrollTo(0,676.5)")
        self.driver.find_element(By.LINK_TEXT, "Task Instances").click()
        self.driver.find_element(By.LINK_TEXT, "example_bash_operator").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "#run_this_last > .label-container").click()
        self.driver.find_element(By.ID, "btn_rendered").click()
        self.driver.find_element(By.LINK_TEXT, "Task Reschedules").click()
        self.driver.find_element(By.LINK_TEXT, "Search").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fa-search").click()
        self.driver.find_element(By.LINK_TEXT, "Task Reschedules").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".accordion-toggle > .caret").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".accordion-toggle > .caret").click()
        self.driver.find_element(By.LINK_TEXT, "Triggers").click()
        self.driver.find_element(By.LINK_TEXT, "SLA Misses").click()
        self.driver.find_element(By.LINK_TEXT, "DAG Dependencies").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".node:nth-child(4) > .label-container").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".node:nth-child(1) > .label-container").click()
        self.driver.find_element(By.LINK_TEXT, "Variables").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".form-inline > .btn").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-inline").click()
        self.driver.find_element(By.NAME, "file").click()
        self.driver.find_element(By.NAME, "file").send_keys(
            "C:\\fakepath\\Log at 2022-08-03 11-00-37 AM.txt")
        self.driver.find_element(
            By.CSS_SELECTOR, ".form-inline > .btn").click()
        self.driver.find_element(By.LINK_TEXT, "Connections").click()
        self.driver.find_element(By.LINK_TEXT, "Plugins").click()
        self.driver.find_element(By.LINK_TEXT, "Connections").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".btn-group:nth-child(2) > .btn").click()
        element = self.driver.find_element(By.LINK_TEXT, "Back")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".well").click()
        element = self.driver.find_element(By.LINK_TEXT, "Back")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.ID, "1").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".btn-group:nth-child(2) > .btn").click()
        self.driver.find_element(By.LINK_TEXT, "Duplicate").click()
        element = self.driver.find_element(By.LINK_TEXT, "Duplicate")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.ID, "modal-confirm-ok").click()
        self.driver.find_element(By.ID, "53").click()
        element = self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(1) .fa-edit")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(
            By.CSS_SELECTOR, ".btn-group:nth-child(2) > .btn").click()
        self.driver.find_element(By.LINK_TEXT, "Delete").click()
        element = self.driver.find_element(By.LINK_TEXT, "Delete")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.ID, "modal-confirm-ok").click()
        element = self.driver.find_element(By.ID, "modal-confirm-ok")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.LINK_TEXT, "Providers").click()
        self.driver.find_element(
            By.LINK_TEXT, "apache-airflow-providers-apache-cassandra").click()
        self.driver.find_element(By.LINK_TEXT, "Pools").click()
        self.driver.find_element(By.LINK_TEXT, "default_pool").click()
        self.driver.find_element(By.LINK_TEXT, "push_by_returning").click()
        self.driver.find_element(By.LINK_TEXT, "XComs").click()
        element = self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(1) .material-icons")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(1) .material-icons").click()
        self.driver.find_element(
            By.LINK_TEXT, "REST API Reference (Swagger UI)").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "#operations-EventLog-get_event_logs .opblock-summary-path span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".try-out__btn").click()
        self.driver.find_element(
            By.LINK_TEXT, "REST API Reference (Redoc)").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".sc-biJonm:nth-child(3) > .hLpUhH").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".sc-biJonm:nth-child(12) > .sc-eHEENL").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".ZHquE > .sc-biJonm:nth-child(1) > .emrRcd > .sc-hzUIXc").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".ZHquE > .sc-biJonm:nth-child(2) > .emrRcd > .sc-hzUIXc").click()
        self.driver.find_element(By.CSS_SELECTOR, ".brand-logo > path").click()
        self.driver.find_element(By.LINK_TEXT, "Permissions").click()
        self.driver.find_element(By.LINK_TEXT, "2").click()
        self.driver.find_element(By.LINK_TEXT, "Resources").click()
        self.driver.find_element(By.LINK_TEXT, "2").click()
        self.driver.find_element(By.LINK_TEXT, "Actions").click()
        self.driver.find_element(By.LINK_TEXT, "User\'s Statistics").click()
        self.driver.find_element(By.LINK_TEXT, "Login Count").click()
        self.driver.find_element(By.LINK_TEXT, "Failed Login Count").click()
        self.driver.find_element(By.LINK_TEXT, "List Roles").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".btn-group:nth-child(2) > .btn").click()
        element = self.driver.find_element(By.LINK_TEXT, "Show")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.ID, "3").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".btn-group:nth-child(2) > .btn").click()
        self.driver.find_element(By.LINK_TEXT, "Copy Role").click()
        element = self.driver.find_element(By.LINK_TEXT, "Copy Role")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.ID, "modal-confirm-ok").click()
        self.driver.execute_script("window.scrollTo(0,557)")
        element = self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(5) .btn:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.ID, "6").click()
        element = self.driver.find_element(
            By.CSS_SELECTOR, ".success .btn:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        element = self.driver.find_element(
            By.CSS_SELECTOR, ".success .btn:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        element = self.driver.find_element(
            By.CSS_SELECTOR, ".success .confirm")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".success .confirm").click()
        self.driver.find_element(By.ID, "modal-confirm-ok").click()
        self.driver.find_element(By.LINK_TEXT, "List Users").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fa-plus").click()
        self.driver.find_element(By.ID, "first_name").click()
        self.driver.find_element(By.ID, "first_name").send_keys("Test")
        self.driver.find_element(By.ID, "last_name").send_keys("Demo")
        self.driver.find_element(By.ID, "username").send_keys("test_demo")
        self.driver.find_element(By.ID, "active").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(
            By.ID, "email").send_keys("test@rapidfort.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("Fiery.123")
        self.driver.find_element(By.ID, "conf_password").send_keys("Fiery.123")
        self.driver.find_element(By.CSS_SELECTOR, ".well").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fa-save").click()
        self.driver.find_element(By.ID, "s2id_autogen1").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(7) > td:nth-child(2)").click()
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("Fiery.123")
        self.driver.find_element(By.ID, "conf_password").send_keys("Fiery.123")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "List Users").click()
        self.driver.find_element(By.LINK_TEXT, "DAGs").click()
        element = self.driver.find_element(
            By.CSS_SELECTOR, ".active:nth-child(3) > .js-tooltip")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        element = self.driver.find_element(By.LINK_TEXT, "Active 27")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "Active 27").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(1) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(2) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(3) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(4) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(5) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(1)").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(6) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(7) .switch").click()
        self.driver.execute_script("window.scrollTo(0,316)")
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(8) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(9) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(10) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(11) .switch").click()
        self.driver.execute_script("window.scrollTo(0,527)")
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(12) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(13) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(14) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(15) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(16) .switch").click()
        element = self.driver.find_element(By.LINK_TEXT, "«")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(27) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(26) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(25) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(24) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(23) > td:nth-child(1)").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(23) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(22) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(21) .switch").click()
        self.driver.execute_script("window.scrollTo(0,1153.5)")
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(17) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(18) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(19) .switch").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(20) .switch").click()
        self.driver.execute_script("window.scrollTo(0,906.5)")
        element = self.driver.find_element(By.LINK_TEXT, "All 27")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(
            By.CSS_SELECTOR, ".btn:nth-child(1) > .badge").click()
        self.driver.find_element(
            By.LINK_TEXT, "account_circleYour Profile").click()
        self.driver.find_element(By.LINK_TEXT, "Reset my password").click()
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("Fiery.123")
        self.driver.find_element(By.ID, "conf_password").send_keys("Fiery.123")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Edit User").click()
        self.driver.find_element(By.ID, "first_name").click()
        self.driver.find_element(By.ID, "first_name").send_keys("Firstname2")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "strong")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "exit_to_appLog Out").click()
        self.driver.close()
