version: '3'

services:
  podman:
    image: ${PODMAN_IMAGE_REPOSITORY}:${PODMAN_IMAGE_TAG}
    user: root
    cap_add:
      - SYS_PTRACE
      - SETUID
      - SETGID
    privileged: true
    volumes:
      - ./coverage.sh:/tmp/coverage.sh
      - ./node.yml:/tmp/node.yml
      - ./Dockerfile:/home/podman/Dockerfile
    stdin_open: true
    tty: true
    entrypoint: /bin/bash