version: '2'

services:
  hadolint:
    image: ${HADOLINT_IMAGE_REPOSITORY}:${HADOLINT_IMAGE_TAG}
    user: root
    cap_add:
      - SYS_PTRACE
    entrypoint:
      - "sleep"
    command:
      - "infinity"
    volumes:
      - ./hadolint_tests/hadolint.yml:root/.config/hadolint.yml
      
