# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGhost():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_ghost(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(929, 791)
    self.driver.find_element(By.LINK_TEXT, "About").click()
    self.driver.get("http://localhost:8080/ghost")
    self.driver.find_element(By.ID, "identification").send_keys("user@example.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("bitnami123")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.ID, "ember48")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "ember48").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gh-btn-green > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".gh-members-help-card:nth-child(1) .thumbnail")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "ember20").click()
    self.driver.find_element(By.CSS_SELECTOR, "#ember97 > span").click()
    self.driver.find_element(By.ID, "ember109").send_keys("rapidfort")
    element = self.driver.find_element(By.CSS_SELECTOR, ".koenig-editor__editor")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p data-koenig-dnd-droppable=\"true\">hello</p>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, ".darkgrey > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gh-publish-setting:nth-child(1) .gh-publish-setting-trigger > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(2) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gh-btn-black > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "#ember127 > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#ember127 > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, "img").click()
    self.vars["win742"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win742"])
    self.driver.execute_script("window.scrollTo(0,0)")
  
