# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPrimaryFunctions():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_primaryFunctions(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(1846, 1053)
    self.driver.find_element(By.LINK_TEXT, "About").click()
    self.driver.get("http://localhost:8080/ghost")
    self.driver.find_element(By.ID, "identification").click()
    self.driver.find_element(By.ID, "identification").send_keys("user@example.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("bitnami123")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    self.driver.get("http://localhost:8080ghost/#/members")
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Add yourself as a member to test\')]").click()
    self.driver.get("http://localhost:8080/ghost/#/editor/post")
    self.driver.find_element(By.XPATH, "//textarea").send_keys("Sample RF")
    element = self.driver.find_element(By.XPATH, "//article/div/div")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p data-koenig-dnd-droppable=\"true\">Hello</p><p data-koenig-dnd-droppable=\"true\"><br></p>'}", element)
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Publish\')]").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Continue, final review →\')]").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Publish post, right now\')]").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".gh-post-bookmark-title").click()
    self.vars["win3910"] = self.wait_for_window(2000)
    self.driver.get("http://localhost:8080/ghost/#/settings")
    self.driver.get("http://localhost:8080ghost/#/settings/design")
    self.driver.get("http://localhost:8080/ghost/#/settings/analytics")
    self.driver.close()
  
