alertmanager:
  containerSecurityContext:
    runAsNonRoot: false
    privileged: true
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true

server:
  containerSecurityContext:
    runAsNonRoot: false
    privileged: true
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
  args:
    - --config.file=/opt/bitnami/prometheus/conf/prometheus.yaml                                                                              
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention.time=10d                                                                                                       
    - --storage.tsdb.retention.size=0
    - --log.level=info                                                                                                                        
    - --log.format=logfmt
    - --web.listen-address=:9090                                                                                                              
    - --web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries
    - --web.console.templates=/opt/bitnami/prometheus/conf/consoles                                                                           
    - --web.route-prefix=/
  configuration: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        monitor: 'my-project'
  
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 15s
        static_configs:
          - targets: ['localhost:9090']
  
  thanos:
    create: true
    image:
      pullSecrets: ["rf-regcred"]
      pullPolicy: Always

    containerSecurityContext:
      enabled: true
      runAsUser: 0
      runAsGroup: 0
      runAsNonRoot: false
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: true
      capabilities:
        add: ["SYS_PTRACE"]
    extraEnvVars:
      - name: "RF_VERBOSE"
        value: "0"
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 30
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 30