version: '2'

services:
  fluent-bit:
    image: ${FLUENT_BIT_IMAGE_REPOSITORY}:${FLUENT_BIT_IMAGE_TAG}
    cap_add:
      - SYS_PTRACE
    ports:
      - '0.0.0.0::2020'
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./config/fluent-bit.config:/tmp/fluent-bit.config
      - ./config/plugins.config:/fluent-bit/etc/plugin.config
    networks:
      - elastic

  elasticsearch:
    image: rapidfort/elasticsearch:8.13
    ports:
      - 9200:9200
    volumes:
      - 'elasticsearch_data:/tmp/elasticsearch'
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

volumes:
  elasticsearch_data:
    driver: local

networks:
  elastic:
    driver: bridge