apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: localhost-server
  namespace: ci-dev
spec:
  secretName: localhost-server-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - rapidfort
  commonName: localhost
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - localhost
  ipAddresses:
    - 127.0.0.1
  # Issuer references are always required.
  issuerRef:
    name: ci-ca-issuer
    kind: Issuer
    group: cert-manager.io
