apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ci-selfsigned-ca
spec:
  isCA: true
  commonName: ci-selfsigned-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ci-ca-issuer
spec:
  ca:
    secretName: root-secret
