site_name: My Docs Title
repo_url: https://github.com/rapidfort/community-images/
repo_name: "community-images"
edit_uri: root/path/docs/
lang: ru
nav:
  - Home: "index.md"
  - Pags: 
    - Page: "page.md"
    - Sub: "sub.md"
markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
theme: 
  name: material
  analytics:
    gtag: G-ABC123
  prev_next_buttons_location: bottom
  logo: img/Rapidfort-logo.png
  highlightjs: true
  hljs_languages:
    - c#
    - css
    - javascript
    - js
    - php

