version: '3'
services:
  elasticsearch:
    image: rapidfort/elasticsearch:8.13.2
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - "discovery.type=single-node"
  
  heartbeat:
    image: ${HEARTBEAT_IMAGE_REPOSITORY}:${HEARTBEAT_IMAGE_TAG}
    user: root
    cap_add:
      - SYS_PTRACE
    volumes:
      - "./heartbeat.docker.yml:/usr/share/heartbeat/heartbeat.yml"
    command: -e --strict.perms=false
    depends_on:
      - elasticsearch
      - myhost

  myhost:
    image: python:latest
    user: root
    command:
      - /bin/bash
      - -c
      - |
        python3 -m http.server --directory / 80

