output:
  elasticsearch:
    hosts: ["elasticsearch:9200"]

heartbeat.monitors:
- type: icmp
  schedule: '*/5 * * * * * *' 
  hosts: ["myhost"]
  id: my-icmp-service
  name: My ICMP Service
- type: tcp
  schedule: '@every 5s' 
  hosts: ["myhost:80"]
  mode: any 
  id: my-tcp-service
- type: http
  schedule: '@every 5s'
  urls: ["http://myhost"]
  service.name: apm-service-name 
  id: my-http-service
  name: My HTTP Service
