version: '2'

services:
  bats:
    image: ${BATS_IMAGE_REPOSITORY}:${BATS_IMAGE_TAG}
    user: root
    cap_add:
      - SYS_PTRACE
    entrypoint:
      - "sleep"
    command:
      - "infinity"
    volumes:
      - ./test:/tmp
    
