global:
  image:
    pullSecrets: ["rf-regcred"]
    pullPolicy: Always
  containerSecurityContext:
    enabled: true
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    capabilities:
      add: ["SYS_PTRACE"]
  extraEnvVars:
    - name: "RF_VERBOSE"
      value: "0" 
  livenessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 30
  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 30
controller:
  containerSecurityContext:
    readOnlyRootFilesystem: false
    capabilities:
      add: ["SYS_PTRACE"]
dex:
  containerSecurityContext:
    readOnlyRootFilesystem: false
    capabilities:
      add: ["SYS_PTRACE"]
server:
  containerSecurityContext:
    readOnlyRootFilesystem: false
    capabilities:
      add: ["SYS_PTRACE"]
repoServer:
  containerSecurityContext:
    readOnlyRootFilesystem: false
    capabilities:
      add: ["SYS_PTRACE"] 
applicationSet: 
  containerSecurityContext:
    readOnlyRootFilesystem: false
    capabilities:
      add: ["SYS_PTRACE"]
notifications:
  containerSecurityContext:
    readOnlyRootFilesystem: false
    capabilities:
      add: ["SYS_PTRACE"]
redisSecretInit:
  containerSecurityContext:
    readOnlyRootFilesystem: false
    capabilities:
      add: ["SYS_PTRACE"]
  

