# Generated by Selenium IDE
# pylint: skip-file

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestYourlsuitest():
    def setup_method(self, method):  # pylint: disable=unused-argument
        """setup method."""
        chrome_options = Options()
        chrome_options.add_argument("--headless")
        chrome_options.add_argument('--disable-dev-shm-usage')
        chrome_options.add_argument("disable-infobars")
        chrome_options.add_argument("--disable-extensions")
        chrome_options.add_argument("--disable-gpu")
        chrome_options.add_argument("--no-sandbox")
        self.driver = webdriver.Chrome(
            options=chrome_options)  # pylint: disable=attribute-defined-outside-init
        self.driver.implicitly_wait(10)

    def teardown_method(self, method):  # pylint: disable=unused-argument
        """teardown method."""
        self.driver.quit()
  
    def test_yourlsuitest(self, params):
        # Navigating to Initial Installation Page
        self.driver.get("http://localhost:{}/".format(params["port"]))
        self.driver.set_window_size(818, 694)
        self.driver.find_element(By.LINK_TEXT, "Administration Console").click()
        self.driver.find_element(By.ID, "username").send_keys("admin")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("admin")
        self.driver.find_element(By.ID, "kc-login").click()
        self.driver.find_element(By.LINK_TEXT, "Clients").click()
        self.driver.find_element(By.ID, "createClient").click()
        self.driver.find_element(By.ID, "clientId").send_keys("test")
        self.driver.find_element(By.CSS_SELECTOR, ".col-md-10 > .btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Roles").click()
        self.driver.find_element(By.ID, "createRole").click()
        self.driver.find_element(By.ID, "name").click()
        self.driver.find_element(By.ID, "name").send_keys("test-role")
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) .btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Users").click()
        self.driver.find_element(By.ID, "createUser").click()
        self.driver.find_element(By.ID, "username").click()
        self.driver.find_element(By.ID, "username").send_keys("rapiduser")
        self.driver.find_element(By.CSS_SELECTOR, ".col-md-10:nth-child(1) > .btn-primary").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav-category:nth-child(3) li:nth-child(1) > .ng-binding").click()
        self.driver.execute_script("window.scrollTo(0,14)")
        self.driver.find_element(By.LINK_TEXT, "Sessions").click()
        self.driver.find_element(By.LINK_TEXT, "Events").click()
        self.driver.get("http://localhost:{}/admin/master/console/#/realms/master".format(params["port"]))
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(7) .onoffswitch-inactive").click()
        self.driver.find_element(By.LINK_TEXT, "User Federation").click()
        self.driver.get("http://localhost:{}/admin/master/console/#/create/realm".format(params["port"]))
        self.driver.find_element(By.ID, "name").click()
        self.driver.find_element(By.ID, "name").send_keys("test-realm")
        self.driver.find_element(By.CSS_SELECTOR, ".col-md-10 > .btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Admin").click()
        self.driver.find_element(By.LINK_TEXT, "Sign Out").click()