version: '2'  # Specify Docker Compose version (adjust if needed)

services:
  # PostgreSQL service
  postgres:
    image: postgres:latest  # Use latest PostgreSQL image (or specify a version)
    environment:
      POSTGRES_PASSWORD: mysecretpassword  # Set your desired password (replace with a strong one)
    ports:
      - 5432:5432

  # pgAdmin service
  pgadmin:
    image: ${PGADMIN_IMAGE_REPOSITORY}:${PGADMIN_IMAGE_TAG} # Use official pgAdmin4 image
    user: root
    cap_add:
      - SYS_PTRACE
    ports:
      - 8080:80  # Map container port 80 to host port 5050 (adjust if needed)
    environment:
      PGADMIN_DEFAULT_EMAIL: sample@example.com  # Optional: Set default email for pgAdmin
      PGADMIN_DEFAULT_PASSWORD: pass_123  # Set a password for pgAdmin (replace with a strong one)


