version: '3'

services:
  sqlite3:
    image: ${SQLITE_IMAGE_REPOSITORY}:${SQLITE_IMAGE_TAG}
    user: root
    cap_add:
      - SYS_PTRACE 
    stdin_open: true
    tty: true
    volumes:
      - ./test.sql:/tmp/test.sql