global:
  image:
    pullSecrets: ["rf-regcred"]
    pullPolicy: Always
  extraEnvVars:
    - name: "RF_VERBOSE"
      value: "0" 
  livenessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 30
  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 30
controller:
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    capabilities:
      add: ["SYS_PTRACE"]    
dex:
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    capabilities:
      add: ["SYS_PTRACE"]
server:
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: false
    capabilities:
      add: ["SYS_PTRACE"]
repoServer:
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    capabilities:
      add: ["SYS_PTRACE"] 
server:
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    capabilities:
      add: ["SYS_PTRACE"] 
repoServer:
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    capabilities:
      add: ["SYS_PTRACE"]  
applicationSet: 
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    capabilities:
      add: ["SYS_PTRACE"] 
notifications:
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    capabilities:
      add: ["SYS_PTRACE"] 
redisSecretInit:
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    capabilities:
      add: ["SYS_PTRACE"] 
  