"""The selenium test."""
# pylint: skip-file

# Generated by Selenium IDE
import json  # pylint: disable=import-error disable=unused-import
import time  # pylint: disable=import-error disable=unused-import
import pytest  # pylint: disable=import-error disable=unused-import
from selenium import webdriver  # pylint: disable=import-error
from selenium.webdriver.chrome.options import Options  # pylint: disable=import-error
from selenium.webdriver.common.by import By  # pylint: disable=import-error
from selenium.webdriver.common.action_chains import ActionChains  # pylint: disable=import-error disable=unused-import
from selenium.webdriver.support import expected_conditions  # pylint: disable=import-error disable=unused-import
from selenium.webdriver.support.wait import WebDriverWait  # pylint: disable=import-error disable=unused-import
from selenium.webdriver.common.keys import Keys  # pylint: disable=import-error disable=unused-import
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities  # pylint: disable=import-error disable=unused-import


class TestWordpresstest1():
    """The test word press class for testing wordpress image."""

    def setup_method(self, method):  # pylint: disable=unused-argument
        """setup method."""
        chrome_options = Options()
        chrome_options.add_argument("--headless")
        chrome_options.add_argument('--disable-dev-shm-usage')
        chrome_options.add_argument("disable-infobars")
        chrome_options.add_argument("--disable-extensions")
        chrome_options.add_argument("--disable-gpu")
        chrome_options.add_argument("--no-sandbox")
        self.driver = webdriver.Chrome(
            options=chrome_options)  # pylint: disable=attribute-defined-outside-init
        self.driver.implicitly_wait(10)

    def teardown_method(self, method):  # pylint: disable=unused-argument
        """teardown method."""
        self.driver.quit()

    def test_initializationdatabases(self, params):
        # Test name: initialization_databases
        # Step # | name | target | value |
        # 1 | open | /wp-admin/setup-config.php |
        self.driver.get(
                "http://localhost:{}/wp-admin/setup-config.php".format(
                    params["port"]))  # pylint: disable=consider-using-f-string
        # 2 | setWindowSize | 727x785 |
        self.driver.set_window_size(727, 785)
        # 3 | click | id=language-continue |
        self.driver.find_element(By.ID, "language-continue").click()
        # 4 | click | linkText=Let’s go! |
        self.driver.find_element(By.LINK_TEXT, "Let’s go!").click()
        # 5 | click | id=dbname |
        self.driver.find_element(By.ID, "dbname").click()
        # 6 | type | id=dbname | ironbank_wordpress | 
        self.driver.find_element(By.ID, "dbname").send_keys("ironbank_wordpress")
        # 7 | click | id=uname |
        self.driver.find_element(By.ID, "uname").click()
        # 8 | type | id=uname | ib_wordpress | 
        self.driver.find_element(By.ID, "uname").send_keys("ib_wordpress")
        # 9 | click | id=dbhost |
        self.driver.find_element(By.ID, "dbhost").click()
        # 10 | type | id=dbhost | mariadb | 
        self.driver.find_element(By.ID, "dbhost").send_keys("\b\b\b\b\b\b\b\b\bmariadb")
        # 11 | click | name=submit |
        self.driver.find_element(By.NAME, "submit").click()
        # 12 | click | linkText=Run the installation |
        self.driver.find_element(By.LINK_TEXT, "Run the installation").click()
        
        # 13 | open | /wp-admin/install.php?language=en_US |
        self.driver.get(
            "http://localhost:{}/wp-admin/install.php?language=en_US".format(
                params["port"]))  # pylint: disable=consider-using-f-string

        # 14 | click | id=weblog_title |
        self.driver.find_element(By.ID, "weblog_title").click()
        # 15 | type | id=weblog_title | rf-site-wordpress-ib | 
        self.driver.find_element(By.ID, "weblog_title").send_keys("rf-site-wordpress-ib")
        # 16 | click | id=user_login |
        self.driver.find_element(By.ID, "user_login").click()
        # 17 | type | id=user_login | ib_wordpress_user | 
        self.driver.find_element(By.ID, "user_login").send_keys("ib_wordpress_user")
        # 18 | click | id=admin_email |
        self.driver.find_element(By.ID, "admin_email").click()
        # 19 | type | id=admin_email | my@mymail.com | 
        self.driver.find_element(By.ID, "admin_email").send_keys("my@mymail.com")
        # 20 | click | id=submit |
        self.driver.find_element(By.ID, "submit").click()

    def test_wordpresstest1(self, params):
        """test wordpress."""
        # Test name: wordpress-test-1
        # Step # | name | target | value
        # 1 | open | / |
        self.driver.get(
            "http://localhost:{}/".format(
                params["port"]))  # pylint: disable=consider-using-f-string
        # 2 | setWindowSize | 1095x688 |
        self.driver.set_window_size(1095, 688)
        # 3 | click | linkText=Hello world! |
        self.driver.find_element(By.LINK_TEXT, "Hello world!").click()
        # 4 | click | id=comment |
        self.driver.find_element(By.ID, "comment").click()
        # 5 | type | id=comment | hello
        self.driver.find_element(By.ID, "comment").send_keys("hello")
        # 6 | click | id=author |
        self.driver.find_element(By.ID, "author").click()
        # 7 | type | id=author | hello
        self.driver.find_element(By.ID, "author").send_keys("hello")
        # 8 | type | id=email | hello@abc.com
        self.driver.find_element(By.ID, "email").send_keys("hello@abc.com")
        # 9 | type | id=url | http://hello.com
        self.driver.find_element(By.ID, "url").send_keys("http://hello.com")
        # 10 | click | id=submit |
        self.driver.find_element(By.ID, "submit").click()

    def test_simplelogin(self, params):
        """Test name: simplelogin."""
        # Step # | name | target | value
        # 1 | open | /wp-login.php |
        self.driver.get(
            "http://localhost:{}/wp-login.php".format(
                params["port"]))  # pylint: disable=consider-using-f-string
        # 2 | setWindowSize | 1200x828 |
        self.driver.set_window_size(1200, 828)
        # 3 | type | id=user_login | user
        self.driver.find_element(By.ID, "user_login").send_keys("user")
        # 4 | type | id=user_pass | bitnami
        self.driver.find_element(By.ID, "user_pass").send_keys("bitnami")
        # 5 | click | id=wp-submit |
        self.driver.find_element(By.ID, "wp-submit").click()
