version: '3.8'

services:
  redis-master:
    image: rapidfort/redis-official:latest
    container_name: redis-master
    ports:
      - "6379"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "my_password"]
    volumes:
      - redis-master-data:/data

  redis-slave:
    image: rapidfort/redis-official:latest
    container_name: redis-slave
    ports:
      - "6380"
    command: ["redis-server", "--appendonly", "yes", "--slaveof", "redis-master", "6379", "--masterauth", "my_password", "--requirepass", "my_password"]
    depends_on:
      - redis-master
    volumes:
      - redis-slave-data:/data

  redis-exporter:
    image: ${REDIS_EXP_IMAGE_REPOSITORY}:${REDIS_EXP_IMAGE_TAG}
    container_name: redis-exporter
    user: root
    cap_add:
      - SYS_PTRACE
    ports:
      - "9121"

    command: [
      "--redis.addr=redis://redis-master:6379,redis://redis-slave:6379",
      "--redis.addr=redis://redis-slave:6379",
      "--redis.password=my_password",
      "--check-keys=db0=key1,db0=counter",
      "--check-single-keys=db0=key1,db0=counter",
      "--ping-on-connect",
      "--include-system-metrics",
      "--log-format=json",
      "--debug"
    ]
    depends_on:
      - redis-master
      - redis-slave

volumes:
  redis-master-data:
    driver: local
  redis-slave-data:
    driver: local
