name: 🐞 Bug
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - codervinod
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue. Before you open the bug report please review the following troubleshooting guide:
          - [Troubleshoot RapidFort Community Images Issues](https://github.com/rapidfort/community-images/blob/main/TROUBLE_SHOOTING.md)

        Please fill in as much of the following form as you're able.
  - type: input
    id: affected_image
    attributes:
      label: Name and Version
      description: Name and version of the affected chart
      placeholder: rapidfort/postgresql 1.2.3
    validations:
      required: true
  - type: checkboxes
    id: runtime
    attributes:
      label: Which runtime are you using to reproduce this issue?
      description: You may select more than one.
      options:
        - label: Kubernetes
        - label: Docker Compose
        - label: Docker
  - type: dropdown
    id: non_hardened_reproducible
    attributes:
      label: Is this issue reproducible on the original source image?
      description: Please select one
      options:
        - Reproducible
        - Not reproducible
        - Unknown
    validations:
      required: true
  - type: dropdown
    id: bug_type
    attributes:
      label: Could you please identify the category? Details in TROUBLE_SHOOTING.md
      description: Please select one
      options:
        - Coverage Script
        - RF Hardening
        - Source image usage
        - Source image behavior
        - Unknown
    validations:
      required: true
  - type: textarea
    attributes:
      label: What steps will reproduce the bug?
      description: Enter details about your bug.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Are you using any custom parameters or values?
      description: Add any parameter used via `--set` or as a `values.yaml` customization.
  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: If possible please provide textual output instead of screenshots.
  - type: textarea
    attributes:
      label: What do you see instead?
      description: If possible please provide textual output instead of screenshots.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Tell us anything else you think we should know.