name: 🐞 Bug
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue. Before you open the bug report please review the following troubleshooting guide:
          - [Troubleshoot RapidFort Community Images Issues](https://github.com/rapidfort/community-images/blob/main/TROUBLE_SHOOTING.md)

        Please fill in as much of the following form as you're able.
  - type: input
    id: affected_image
    attributes:
      label: Name and Version
      description: Name and version of the affected chart
      placeholder: rapidfort/postgresql 1.2.3
    validations:
      required: true
  - type: checkboxes
    id: runtime
    attributes:
      label: Which runtime are you using to reproduce this issue?
      description: You may select more than one.
      multiple: true
      options:
        - label: Kubernetes
        - label: Docker Compose
        - label: Docker
