version: '2'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    user: root
    cap_add:
      - SYS_PTRACE
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: kphull/kafka-ib:3.4.0-rfstub
    user: root
    cap_add:
      - SYS_PTRACE
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

