version: '2'

services:
  elasticsearch-ib-elastic-elasticsearch:
    image: ${ELASTICSEARCH_IMAGE_REPOSITORY}:${ELASTICSEARCH_IMAGE_TAG}
    container_name: es-bcontainer
    cap_add:
      - SYS_PTRACE
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-bnet   
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'

networks:
  es-bnet:
    driver: bridge
          
volumes:
  elasticsearch_data:
    driver: local
