version: '2'

services:
  nginx:
    image: ${NGINX_IMAGE_REPOSITORY}:${NGINX_IMAGE_TAG}
    user: root
    cap_add:
      - SYS_PTRACE
    ports:
      - '0.0.0.0::8080'
      - '0.0.0.0::8443'
    volumes:
      - ./configs/server_block_backends.conf:/opt/bitnami/nginx/conf/server_blocks/server_block_backends.conf:ro
      - ./configs/server_include_backends.conf:/opt/bitnami/nginx/conf/bitnami/server_include_backends.conf:ro
      - ./coverage_script.sh:/opt/bitnami/scripts/coverage_script.sh
    environment:
      - RF_ACCESS_TOKEN=${RF_ACCESS_TOKEN}  
  backend1a:
    image: nginxdemos/hello:plain-text
    cap_add:
      - SYS_PTRACE
    ports:
      - '80'
  backend1b:
    image: nginxdemos/hello:plain-text
    cap_add:
      - SYS_PTRACE
    ports:
      - '80'
  backend2a:
    image: nginxdemos/hello:plain-text
    cap_add:
      - SYS_PTRACE
    ports:
      - '80'
  backend2b:
    image: nginxdemos/hello:plain-text
    cap_add:
      - SYS_PTRACE
    ports:
      - '80'
