version: '2'

services:
  prometheus:
    image: prom/prometheus:v2.53.1
    ports:
      - '9090:9090'

  alertmanager:
    image: prom/alertmanager:v0.20.0
    ports:
      - '9093:9093'

  grafana-ib:
    image: ${GRAFANA_IMAGE_REPOSITORY}:${GRAFANA_IMAGE_TAG}
    cap_add:
      - SYS_PTRACE
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin@$123
    ports:
      - '3000:3000'
  
