metricbeat.config.modules.path: ${path.config}/modules.d/*.yml
reload.enabled: false
metricbeat.modules:
  - module: elasticsearch
    metricsets:
      - node
      - node_stats
      - cluster_stats
    period: 10s
    hosts: ["http://elasticsearch:9200"]
    # xpack.monitoring.collection.enabled: true

# setup.kibana:
#   host: "localhost:5601"
# setup.kibana.protocol: "http"
# setup.kibana.path: /kibana

host: http://elasticsearch:5601
monitoring.enabled: true
xpack.monitoring.collection.enabled: true
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"] ## Monitoring cluster
  # Optional protocol and basic auth credentials.
  #protocol: "https"
  #username: "elastic"
  #password: "changeme"