version: '2'
services:
  influxdb:
    image: ${INFLUXDB_IMAGE_REPOSITORY}:${INFLUXDB_IMAGE_TAG}
    cap_add:
      - SYS_PTRACE    
    ports:
      - 8086:8086
      - 8088:8088
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=bitnami123
      - INFLUXDB_ADMIN_USER_TOKEN=admintoken123
      - INFLUXDB_USER=my_user
      - INFLUXDB_USER_PASSWORD=my_password
      - INFLUXDB_DB=my_database
    volumes:
      - influxdb_data:/bitnami/influxdb
volumes:
  influxdb_data:
    driver: local
