version: '2'

services:
  nginx:
    image: ${NGINX_OFFICIAL_IMAGE_REPOSITORY}:${NGINX_OFFICIAL_IMAGE_TAG}
    user: root
    cap_add:
      - SYS_PTRACE
    ports:
      - '0.0.0.0::8080'
      - '0.0.0.0::8443'
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./coverage_script.sh:/opt/scripts/coverage_script.sh
      - ./certs:/certs
  backend1a:
    image: nginxdemos/hello:plain-text
    cap_add:
      - SYS_PTRACE
    ports:
      - '80'
  backend1b:
    image: nginxdemos/hello:plain-text
    cap_add:
      - SYS_PTRACE
    ports:
      - '80'
  backend2a:
    image: nginxdemos/hello:plain-text
    cap_add:
      - SYS_PTRACE
    ports:
      - '80'
  backend2b:
    image: nginxdemos/hello:plain-text
    cap_add:
      - SYS_PTRACE
    ports:
      - '80'
