version: '3'
services:
  metabase:
    image: ${METABASE_IMAGE_REPOSITORY}:${METABASE_IMAGE_TAG}
    cap_add:
      - SYS_PTRACE
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
    networks:
      - internal
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  
  postgres:
    image: rapidfort/postgresql12-ib:12.18
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - internal

networks:
  internal:
    driver: bridge


