services:
  jmx-exporter:
    image: ${JMX_EXPORTER_IMAGE_REPOSITORY}:${JMX_EXPORTER_IMAGE_TAG}
    ports:
      - "0.0.0.0::12345"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./jmx-configs:/opt/jmx_exporter/jmx-configs
      - ./jar-files/hello-world.jar:/opt/jmx_exporter/hello-world.jar
      - ./commands.sh:/opt/jmx_exporter/commands.sh