apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rf-redis-cluster-cert
spec:
  commonName: rf-redis-cluster
  duration: 2160h
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: ci-ca-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h
  secretName: rf-redis-cluster-tls
  subject:
    organizations:
    - rapidfort
  usages:
  - server auth
  - client auth
