# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestWordpresstest1():
  def setup_method(self, method):
    chrome_options = Options()
    chrome_options.add_argument("--headless")
    chrome_options.add_argument('--disable-dev-shm-usage')
    chrome_options.add_argument("disable-infobars");
    chrome_options.add_argument("--disable-extensions");
    chrome_options.add_argument("--disable-gpu");
    chrome_options.add_argument("--no-sandbox");
    self.driver = webdriver.Chrome(options=chrome_options)
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_wordpresstest1(self, params):
    # Test name: wordpress-test-1
    # Step # | name | target | value
    # 1 | open | / |
    self.driver.get("http://{}:{}/".format(params["ip_address"], params["port"]))
    #self.driver.get("http://192.168.64.5:30353/")
    # 2 | setWindowSize | 1095x688 |
    self.driver.set_window_size(1095, 688)
    # 3 | click | linkText=Hello world! |
    self.driver.find_element(By.LINK_TEXT, "Hello world!").click()
    # 4 | click | id=comment |
    self.driver.find_element(By.ID, "comment").click()
    # 5 | type | id=comment | hello
    self.driver.find_element(By.ID, "comment").send_keys("hello")
    # 6 | click | id=author |
    self.driver.find_element(By.ID, "author").click()
    # 7 | type | id=author | hello
    self.driver.find_element(By.ID, "author").send_keys("hello")
    # 8 | type | id=email | hello@abc.com
    self.driver.find_element(By.ID, "email").send_keys("hello@abc.com")
    # 9 | type | id=url | http://hello.com
    self.driver.find_element(By.ID, "url").send_keys("http://hello.com")
    # 10 | click | id=submit |
    self.driver.find_element(By.ID, "submit").click()
    # 11 | click | linkText=User's Blog! |
    #self.driver.find_element(By.LINK_TEXT, "User\'s Blog!").click()

