version: '3'
services:
  prometheus:
    image: ${PROMETHEUS_IMAGE_REPOSITORY}:${PROMETHEUS_IMAGE_TAG}
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    cap_add:
      - SYS_PTRACE
    ports:
      - 9090:9090