version: '2'

services:
  terraform:
    image: ${TERRAFORM_IMAGE_REPOSITORY}:${TERRAFORM_IMAGE_TAG}
    user: root
    cap_add:
      - SYS_PTRACE
    entrypoint:
      - "sleep"
    command:
      - "infinity"
    volumes:
      - ./sample_terraform_tf/main.tf:/main.tf
      - /var/run/docker.sock:/var/run/docker.sock  
      - ./terraform_coverage.sh:/terraform_coverage.sh
    network_mode: "host"  