version: '2'

services:
  
  consul-server1:
    image: ${CONSUL_OFFICIAL_IMAGE_REPOSITORY}:${CONSUL_OFFICIAL_IMAGE_TAG}
    user: root
    container_name: consul-server1
    restart: always
    environment:
     - CONSUL_RETRY_JOIN_ADDRESS=consul-server1
    volumes:
     - ./configs/server.json:/server.json
     - ./configs/acls/:/consul/dataconf/acls/
    networks:
      - consul
    cap_add:
      - SYS_PTRACE
    ports:
      - '0.0.0.0::8300'
      - '0.0.0.0::8301'
      - '0.0.0.0::8301/udp'
      - '0.0.0.0::8500'
      - '0.0.0.0::8600'
      - '0.0.0.0::8600/udp'
    command: "consul agent -server -bootstrap-expect=1 -retry-join=consul-server1 -config-file=server.json"

networks:
  consul:
    driver: bridge