version: '2'

services:
  postgres:
    image: rapidfort/postgresql-official:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres-exporter:
    image: ${PG_EXP_IMAGE_REPOSITORY}:${PG_EXP_IMAGE_TAG}
    container_name: postgres-exporter
    user: root
    cap_add:
      - SYS_PTRACE
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:mysecretpassword@postgres:5432/postgres?sslmode=disable"
    ports:
      - "9187"
    depends_on:
      - postgres
    command:
      - '--collector.database'
      - '--collector.database_wraparound'
      - '--collector.locks'
      - '--collector.long_running_transactions'
      - '--collector.postmaster'
      - '--collector.process_idle'
      - '--collector.replication'
      - '--collector.replication_slot'
      - '--collector.stat_activity_autovacuum'
      - '--collector.stat_bgwriter'
      - '--collector.stat_database'
      - '--collector.stat_statements'
      - '--collector.stat_user_tables'
      - '--collector.stat_wal_receiver'
      - '--collector.statio_user_indexes'
      - '--collector.statio_user_tables'
      - '--collector.wal'
      - '--collector.xlog_location'

volumes:
  postgres-data:
    driver: local
