name: traefik-ib
official_name: TRAEFIK Ironbank
official_website: https://traefik.io/
source_image_provider: Platform One
source_image_repo: registry1.dso.mil/ironbank/opensource/traefik/traefik
source_image_repo_link: https://registry1.dso.mil/harbor/projects/3/repositories/opensource%2Ftraefik%2Ftraefik
source_image_readme: https://repo1.dso.mil/dsop/opensource/traefik/traefik/-/blob/development/README.md
rf_docker_link: rapidfort/traefik-ib
image_workflow_name: traefik_ironbank
github_location: traefik/ironbank
report_url: https://frontrow.rapidfort.com/app/community/imageinfo/registry1.dso.mil%2Fironbank%2Fopensource%2Ftraefik%2Ftraefik
usage_instructions: |
  $ helm repo add traefik https://helm.traefik.io/traefik

  # install traefik, just replace repository with RapidFort image.name and the image.tag
  $ helm install traefik traefik/traefik --set image.name=rapidfort/traefik-ib --set image.tag=v2.9.4
what_is_text: |
  Traefik is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy. Traefik integrates with your existing infrastructure components (Docker, Swarm mode, Kubernetes, Marathon, Consul, Etcd, Rancher, Amazon ECS, ...) and configures itself automatically and dynamically. Pointing Traefik at your orchestrator should be the only configuration step you need.
disclaimer: |
  Trademarks: This software listing is packaged by RapidFort. The respective trademarks mentioned in the offering are owned by the respective companies, and use of them does not imply any affiliation or endorsement.
input_registry:
  registry: registry1.dso.mil
  account: ironbank
repo_sets:
  - opensource/traefik/traefik:
      input_base_tag: "2.10."
      output_repo: traefik-ib
runtimes:
  - type: docker_compose
    script: dc_coverage.sh
    compose_file: docker-compose.yml
    wait_time_sec: 10
    tls_certs:
      generate: true
      out_dir: certs
    image_keys:
      traefik-ib:
        repository: "TRAEFIK_IMAGE_REPOSITORY"
        tag: "TRAEFIK_IMAGE_TAG"
