version: '3'

services:
  mongodb:
    image: ${MONGODB_IMAGE_REPOSITORY}:${MONGODB_IMAGE_TAG}
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '::27017'
    volumes:
      - 'mongodb_data_container:/official/mongodb'
      - '../../common/tests/mongodb_coverage.sh:/tmp/mongodb_coverage.sh'
      - './use_mongodb.js:/tmp/use_mongodb.js'
    cap_add:
      - SYS_PTRACE
volumes:
  mongodb_data_container:
    driver: local
