version: '3'

services:
  shellcheck:
    image: ${SHELLCHECK_IMAGE_REPOSITORY}:${SHELLCHECK_IMAGE_TAG}
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./scripts/test_script_success.sh:/mnt/test_script_success.sh:ro
      - ./scripts/test_script_failure.sh:/mnt/test_script_failure.sh:ro
      - ./scripts/test_script2.sh:/mnt/test_script2.sh:ro
      - ./scripts/test_script3.sh:/mnt/test_script3.sh:ro
      - ./scripts/test_script4.sh:/mnt/test_script4.sh:ro
      - ./scripts/test_script5.sh:/mnt/test_script5.sh:ro
      - ./scripts/test_script6.sh:/mnt/test_script6.sh:ro
    entrypoint: ["sleep", "infinity"]
    stdin_open: true
    tty: true
