"""The selenium test."""
# pylint: skip-file

# Generated by Selenium IDE
import json  # pylint: disable=import-error disable=unused-import
import time  # pylint: disable=import-error disable=unused-import
import pytest  # pylint: disable=import-error disable=unused-import
from selenium import webdriver  # pylint: disable=import-error
from selenium.webdriver.chrome.options import Options  # pylint: disable=import-error
from selenium.webdriver.common.by import By  # pylint: disable=import-error
from selenium.webdriver.common.action_chains import ActionChains  # pylint: disable=import-error disable=unused-import
from selenium.webdriver.support import expected_conditions  # pylint: disable=import-error disable=unused-import
from selenium.webdriver.support.wait import WebDriverWait  # pylint: disable=import-error disable=unused-import
from selenium.webdriver.common.keys import Keys  # pylint: disable=import-error disable=unused-import
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities  # pylint: disable=import-error disable=unused-import


class Testmetricui1():
    """The test class for testing metric image."""

    def setup_method(self, method):  # pylint: disable=unused-argument
        """setup method."""
        chrome_options = Options()
        chrome_options.add_argument("--headless")
        chrome_options.add_argument('--disable-dev-shm-usage')
        chrome_options.add_argument("disable-infobars")
        chrome_options.add_argument("--disable-extensions")
        chrome_options.add_argument("--disable-gpu")
        chrome_options.add_argument("--no-sandbox")
        self.driver = webdriver.Chrome(
            options=chrome_options)  # pylint: disable=attribute-defined-outside-init
        self.driver.implicitly_wait(10)

    def teardown_method(self, method):  # pylint: disable=unused-argument
        """teardown method."""
        self.driver.quit()

    def test_initializatin(self):
        self.driver.get("http://localhost:5601/app/monitoring")
        self.driver.set_window_size(1296, 688)
        time.sleep(20)
        # self.driver.find_element(By.CSS_SELECTOR, ".euiHeaderSectionItem > .euiButtonEmpty > .euiButtonEmpty__content").click()
        # self.driver.execute_script("window.scrollTo(0,0)")
        # self.driver.find_element(By.LINK_TEXT, "Stack Monitoring").click()
        self.driver.find_element(By.CSS_SELECTOR, ".css-xv0fhq-euiTextColor-subdued > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".css-8utmkn-euiButtonDisplay-m-defaultMinWidth-fill-primary > .css-1bascr2-euiButtonDisplayContent > span").click()
        self.driver.execute_script("window.scrollTo(0,252.6666717529297)")
        self.driver.execute_script("window.scrollTo(0,0)")
        time.sleep(20)
        self.driver.find_element(By.CSS_SELECTOR, ".euiButtonIcon").click()
        self.driver.find_element(By.CSS_SELECTOR, ".euiFlexItem:nth-child(1) .euiFlexGroup span").click()
        self.driver.find_element(By.LINK_TEXT, "elasticsearch").click()
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(4) > .euiFlexGrid .euiPanel > .euiTitle span").click()
        self.driver.close()