version: '2'

services:
  reverse-proxy:
    image: ${TRAEFIK_IMAGE_REPOSITORY}:${TRAEFIK_IMAGE_TAG}
    # Enables the web UI and tells Traefik to listen to docker
    command:                                                                                                            
      #- "--log.level=DEBUG"                                                                                            
      - "--api.insecure=true"                                                                                           
      - "--providers.docker=true"                                                                                       
      - "--providers.docker.exposedbydefault=false"                                                                     
      - "--entrypoints.web.address=:80"                                                                                 
    ports:                                                                                                              
      # The HTTP port                                                                                                   
      - "80"                                                                                                            
      # The Web UI (enabled by --api.insecure=true)                                                                     
      - "8080" 
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - SYS_PTRACE

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    deploy:
      replicas: 2
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
    cap_add:
      - SYS_PTRACE
