name: traefik
official_name: TRAEFIK
official_website: https://traefik.io/
source_image_provider: Traefik
source_image_repo: docker.io/library/traefik
source_image_repo_link: https://hub.docker.com/_/traefik
source_image_readme: https://github.com/traefik/traefik-library-image/blob/master/README.md
rf_docker_link: rapidfort/traefik
image_workflow_name: traefik_traefik
github_location: traefik/traefik
report_url: https://us01.rapidfort.com/app/community/imageinfo/docker.io%2Flibrary%2Ftraefik
usage_instructions: |
  $ helm repo add traefik https://helm.traefik.io/traefik

  # install traefik, just replace repository with RapidFort image.name and the image.tag
  $ helm install traefik traefik/traefik --set image.name=rapidfort/traefik --set image.tag=v2.9.4
what_is_text: |
  Traefik is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy. Traefik integrates with your existing infrastructure components (Docker, Swarm mode, Kubernetes, Marathon, Consul, Etcd, Rancher, Amazon ECS, ...) and configures itself automatically and dynamically. Pointing Traefik at your orchestrator should be the only configuration step you need.
disclaimer: |
  Trademarks: This software listing is packaged by RapidFort. The respective trademarks mentioned in the offering are owned by the respective companies, and use of them does not imply any affiliation or endorsement.
is_locked: "False"
docker_links:
  - "[`v3.2.5`, `3.2.5`, `v3.2`, `3.2`, `v3`, `3`, `mimolette`](https://github.com/traefik/traefik-library-image/blob/master/v3.2/alpine/Dockerfile)"
  - "[`v3.3.2`, `3.3.2`, `v3.3`, `3.3`, `v3`, `3`, `saintnectaire`, `latest`](https://github.com/traefik/traefik-library-image/blob/4fc0980f9d74f7c3be2ef4bf2513cb39b3d2226b/v3.3/alpine/Dockerfile)"
input_registry:
  registry: docker.io
  account: library
repo_sets:
  - traefik:
      input_base_tag: "v3.3.[0-9.]*$"
  - traefik:
      input_base_tag: "v3.2.[0-9.]*$"
runtimes:
  - type: docker_compose
    script: dc_coverage.sh
    compose_file: docker-compose.yml
    wait_time_sec: 10
    tls_certs:
      generate: true
      out_dir: certs
    image_keys:
      traefik:
        repository: "TRAEFIK_IMAGE_REPOSITORY"
        tag: "TRAEFIK_IMAGE_TAG"

