version: "3"
services:
  vault:
    image: ${VAULT_IMAGE_REPOSITORY}:${VAULT_IMAGE_TAG}
    user: root
    ports:
      - 8200:8200
    volumes:
      - ./policy.hcl:/tmp/policy.hcl
      - vault-data:/vault/file/
    environment:
      - VAULT_ADDR=http://localhost:8200
    cap_add:
      - IPC_LOCK
      - SYS_PTRACE
    command: server -dev

volumes:
  vault-data: