version: '3'

services:
  postgresql:
    image: docker.io/rapidfort/postgresql:10.22
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: docker.io/rapidfort/redis:7.0
    volumes:
      - 'redis_data:/bitnami'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  # airflow-scheduler:
  #   # image: rapidfort/airflow-scheduler:latest
  #   # image: ${AIRFLOW_IMAGE_REPOSITORY}:${AIRFLOW_IMAGE_TAG}
  #   image: kirandeepkhehra/airflow-ib:2.6.2-rfstub
  #   cap_add:
  #     - SYS_PTRACE
  #   command: bash -c "airflow db init && airflow scheduler"
  #   environment:
  #     - AIRFLOW_DATABASE_NAME=bitnami_airflow
  #     - AIRFLOW_DATABASE_USERNAME=bn_airflow
  #     - AIRFLOW_DATABASE_PASSWORD=bitnami1
  #     - AIRFLOW_EXECUTOR=CeleryExecutor
  #     - AIRFLOW_WEBSERVER_HOST=airflow-ib
  #     - AIRFLOW__CORE__LOAD_EXAMPLES=True
  #   volumes:
  #     - "airflow_ib_dags:/opt/airflow/dags"
  #   depends_on:
  #     - postgresql
  #     - redis
  # airflow-worker:
  #   # image: rapidfort/airflow-worker:latest
  #   # image: ${AIRFLOW_IMAGE_REPOSITORY}:${AIRFLOW_IMAGE_TAG}
  #   image: kirandeepkhehra/airflow-ib:2.6.2-rfstub
  #   cap_add:
  #     - SYS_PTRACE
  #   command: airflow celery worker
  #   environment:
  #     - AIRFLOW_DATABASE_NAME=bitnami_airflow
  #     - AIRFLOW_DATABASE_USERNAME=bn_airflow
  #     - AIRFLOW_DATABASE_PASSWORD=bitnami1
  #     - AIRFLOW_EXECUTOR=CeleryExecutor
  #     - AIRFLOW_WEBSERVER_HOST=airflow
  #   depends_on:
  #     - postgresql
  #     - redis
  airflow-ib:
    image: ${AIRFLOW_IMAGE_REPOSITORY}:${AIRFLOW_IMAGE_TAG}
    # image: kirandeepkhehra/airflow-ib:2.6.2-rfstub
    command: bash -c "airflow db init && (airflow webserver & airflow scheduler)"
    cap_add:
      - SYS_PTRACE
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=true
    ports:
      - '8080:8080'
    depends_on:
      - postgresql
      - redis
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  airflow_ib_dags:
    driver: local
