version: '2'

services:
  mariadb:
    image: docker.io/rapidfort/mariadb
    volumes:
      - 'mariadb_data:/ironbank/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=ib_wordpress
      - MARIADB_DATABASE=ironbank_wordpress

  wordpress-ib:
    image: ${WORDPRESS_IMAGE_REPOSITORY}:${WORDPRESS_IMAGE_TAG}

    user: root
    cap_add:
      - SYS_PTRACE
    ports:
      - '8080:8080'
      - '4443:8443'
    volumes:
      - 'wordpress_data:/ironbank/wordpress'
      - ./certs/server.crt:/etc/pki/tls/certs/localhost.crt
      - ./certs/server.key:/etc/pki/tls/private/localhost.key
      - ./certs/server.crt:/usr/local/apache2/conf/server.crt
      - ./certs/server.key:/usr/local/apache2/conf/server.key

    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=ib_wordpress
      - WORDPRESS_DATABASE_NAME=ironbank_wordpress
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
