kind: Pod
apiVersion: v1
metadata:
  labels:
    run: python-chromedriver
  name: python-chromedriver
spec:
  containers:
  - name: python-chromedriver
    image: rapidfort/python-chromedriver:latest
    env:
    - name: SERVER
      value: "10.96.94.219"
    - name: PORT
      value: "443"
    command:
    - /bin/bash
    - -c
    - sleep infinity
