version: '2'
services:
     openldap:
          image: ${OPENLDAP_IMAGE_REPOSITORY}:${OPENLDAP_IMAGE_TAG}
          user: root
          cap_add:
               - SYS_PTRACE
          environment:
               ADMIN_PW: "test123"
               ADMIN_PW_HASH: "e1NTSEF9eVV0UTRZd2lab0lkaVV1N0FDZVRQSDVrRGVEZXd6aDQK"
               TLD: "dc=usaf,dc=mil"
               LDAP_PORT: 2123
          ports:
               - "4000:2123"
          volumes:
               - "./slapd-config:/etc/openldap/slapd-config"
               - "./slapd-data:/openldap/slapd-data"
               - ./openldap_test:/openldap_test
               - ./coverage.sh:/coverage.sh
