version: '2'

services:
  kubectl:
    image: ${KUBECTL_IMAGE_REPOSITORY}:${KUBECTL_IMAGE_TAG}
    user: root
    cap_add:
      - SYS_PTRACE 
    entrypoint:
      - "sleep"  
    command:
      - "infinity"
    environment:
      - KUBECONFIG=/.kube/config
    volumes:
      - ~/.kube/config:/.kube/config
      - /var/run/docker.sock:/var/run/docker.sock
      - ./coverage.sh:/tmp/coverage.sh
    network_mode: "host"   