version: '2'
services:
  elasticsearch:
    image: rapidfort/elasticsearch:8.13
    ports:
      - 9200:9200
    volumes:
      - 'elasticsearch_data:/tmp/elasticsearch'
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - xpack.monitoring.collection.enabled=true
      - xpack.monitoring.elasticsearch.collection.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  kibana:
    image: rapidfort/kibana-ib:latest
    cap_add:
      - SYS_PTRACE
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    networks:
      - elastic    
  auditbeat:
    image: ${AUDITBEAT_IMAGE_REPOSITORY}:${AUDITBEAT_IMAGE_TAG}
    user: root
    pid: host
    cap_add:
      - SYS_PTRACE
      - AUDIT_CONTROL
      - AUDIT_READ
    networks:
      - elastic
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - KIBANA_HOST=http://kibana:5601
    volumes:
      - ./auditbeat.yml:/usr/share/auditbeat/auditbeat.yml
      - auditbeat-data:/usr/share/auditbeat/data
      - ./test_coverage.sh:/usr/share/auditbeat/test_coverage.sh
    command: ["--strict.perms=false"]
    deploy:
      mode: global
    depends_on:
      - elasticsearch  

volumes:
  elasticsearch_data:
    driver: local
  auditbeat-data:
    driver: local  

networks:
  elastic:
    driver: bridge

