# Generated by Selenium IDE
# pylint: skip-file

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestYourlsuitest():
    def setup_method(self, method):  # pylint: disable=unused-argument
        """setup method."""
        chrome_options = Options()
        chrome_options.add_argument("--headless")
        chrome_options.add_argument('--disable-dev-shm-usage')
        chrome_options.add_argument("disable-infobars")
        chrome_options.add_argument("--disable-extensions")
        chrome_options.add_argument("--disable-gpu")
        chrome_options.add_argument("--no-sandbox")
        self.driver = webdriver.Chrome(
            options=chrome_options)  # pylint: disable=attribute-defined-outside-init
        self.driver.implicitly_wait(10)

    def teardown_method(self, method):  # pylint: disable=unused-argument
        """teardown method."""
        self.driver.quit()
  
    def test_yourlsuitest(self, params):
      self.driver.get("http://localhost:{}/admin/install.php".format(params["port"]))
    #   self.driver.get("http://localhost/admin/install.php")
      self.driver.set_window_size(533, 876)
      self.driver.find_element(By.NAME, "install").click()
      self.driver.find_element(By.LINK_TEXT, "YOURLS Administration Page").click()
      self.driver.get("http://localhost:{}/admin/".format(params["port"]))
      self.driver.find_element(By.ID, "username").send_keys("rapidfortbot")
      self.driver.find_element(By.ID, "password").send_keys("rapidpassword")
      self.driver.find_element(By.ID, "submit").click()
      self.driver.find_element(By.ID, "add-url").send_keys("https://www.rapidfort.com")
      self.driver.find_element(By.ID, "add-button").click()
      self.driver.find_element(By.LINK_TEXT, "Manage Plugins").click()
      self.driver.get("http://localhost:{}/admin/pulgins.php".format(params["port"]))
      element = self.driver.find_element(By.CSS_SELECTOR, ".plugin:nth-child(2) > .plugin_author > a")
      actions = ActionChains(self.driver)
      actions.move_to_element(element).perform()
      self.driver.find_element(By.LINK_TEXT, "Activate").click()
      self.driver.find_element(By.LINK_TEXT, "Tools").click()
      self.driver.find_element(By.LINK_TEXT, "Admin interface").click()
      element = self.driver.find_element(By.ID, "clicks-yid1")
      actions = ActionChains(self.driver)
      actions.move_to_element(element).perform()
      self.driver.find_element(By.ID, "statlink-yid1").click()
      self.driver.find_element(By.LINK_TEXT, "Admin interface").click()
      self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
