version: '2'

services:
  consul-node1:
    image: bitnami/consul
    user: root
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
    ports:
      - '0.0.0.0::8300'
      - '0.0.0.0::8301'
      - '0.0.0.0::8301/udp'
      - '0.0.0.0::8500'
      - '0.0.0.0::8600'
      - '0.0.0.0::8600/udp'
    cap_add:
      - SYS_PTRACE
    volumes:
      - 'consul-node1_data:/bitnami'
      - ./server_coverage_script.sh:/opt/bitnami/scripts/coverage_script.sh
      - ./sample_service.json:/consul.d/sample_service.json

  consul-node2:
    image: bitnami/consul
    user: root
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
      - CONSUL_ENABLE_UI=false
    cap_add:
      - SYS_PTRACE
    volumes:
      - 'consul-node2_data:/bitnami'

  consul-node3:
    image: bitnami/consul
    user: root
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
      - CONSUL_ENABLE_UI=true
    cap_add:
      - SYS_PTRACE
    volumes:
      - 'consul-node3_data:/bitnami'

  consul-node4:
    image: bitnami/consul
    user: root
    environment:
      - CONSUL_AGENT_MODE=client
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
      - CONSUL_ENABLE_UI=false
    cap_add:
      - SYS_PTRACE
    volumes:
      - 'consul-node4_data:/bitnami'
      - ./client_coverage_script.sh:/opt/bitnami/scripts/coverage_script.sh
    depends_on:
      - consul-node1

volumes:
  consul-node1_data:
    driver: local
  consul-node2_data:
    driver: local
  consul-node3_data:
    driver: local
  consul-node4_data:
    driver: local
