version: '2'

services:
  
  consul-server1:
    image: ${CONSUL_IMAGE_REPOSITORY}:${CONSUL_IMAGE_TAG}
    user: root
    container_name: consul-server1
    restart: always
    environment:
     - CONSUL_RETRY_JOIN_ADDRESS=consul-server1
    volumes:
     - ./configs/server.json:/server.json
     - ./configs/acls/:/opt/bitnami/consul/conf/acls/
    networks:
      - consul
    cap_add:
      - SYS_PTRACE
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "consul agent -server -bootstrap-expect=1 -retry-join=consul-server1 -config-file=server.json"

networks:
  consul:
    driver: bridge