version: '2'

services:
  envoy:
    image: ${ENVOY_IMAGE_REPOSITORY}:${ENVOY_IMAGE_TAG}
    user: root
    cap_add:
      - SYS_PTRACE
    ports:
      - '0.0.0.0::8080'
      - '0.0.0.0::8443'
    volumes:
      - ./certs:/certs
      - ./configs/envoy.yaml:/opt/bitnami/envoy/conf/envoy.yaml:ro
      - ./coverage_script.sh:/opt/bitnami/scripts/coverage_script.sh:ro
  backend1a:
    image: nginxdemos/hello:plain-text
    ports:
      - '80'
  backend1b:
    image: nginxdemos/hello:plain-text
    ports:
      - '80'
  backend2a:
    image: nginxdemos/hello:plain-text
    ports:
      - '80'
  backend2b:
    image: nginxdemos/hello:plain-text
    ports:
      - '80'
