version: '2'

services:
  ansible:
    image: ${ANSIBLE_IMAGE_REPOSITORY}:${ANSIBLE_IMAGE_TAG}
    user: root
    cap_add:
      - SYS_PTRACE
    entrypoint:
      - "sleep"
    command:
      - "infinity"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    network_mode: "host"
    depends_on:
      - ubuntu_host  

  ubuntu_host:
    image: ubuntu:latest
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - "sleep"
    command:
      - "infinity"  