name: ansible-ib
official_name: Ansible IronBank
official_website: https://www.ansible.com/
source_image_provider: Platform One
source_image_repo: registry1.dso.mil/ironbank/opensource/ansible/ansible
source_image_repo_link: https://registry1.dso.mil/harbor/projects/3/repositories/opensource%2Fansible%2Fansible
source_image_readme: https://repo1.dso.mil/dsop/opensource/ansible/ansible/-/blob/development/README.md
rf_docker_link: rapidfort/ansible-ib
image_workflow_name: ansible_ironbank
github_location: ansible/ironbank
report_url: https://us01.rapidfort.com/app/community/imageinfo/registry1.dso.mil%2Fironbank%2Fopensource%2Fansible%2Fansible
usage_instructions: |
  $ docker run --rm -it rapidfort/ansible-ib:latest
what_is_text: |
  Ansible is a radically simple IT automation system. It handles configuration management, application deployment, cloud provisioning, ad-hoc task execution, network automation, and multi-node orchestration. Ansible makes complex changes like zero-downtime rolling updates with load balancers easy. disclaimer: |
Disclaimer:
  Trademarks: This software listing is packaged by RapidFort. The respective trademarks mentioned in the offering are owned by the respective companies, and use of them does not imply any affiliation or endorsement.
docker_links:
  - "[`latest` (Dockerfile)](https://repo1.dso.mil/dsop/opensource/ansible/ansible/-/blob/development/Dockerfile)"
input_registry:
  registry: registry1.dso.mil
  account: ironbank
repo_sets:
  - opensource/ansible/ansible:
      input_base_tag: "10.0."
      output_repo: ansible-ib
runtimes:
  - type: docker_compose
    script: dc_coverage.sh
    compose_file: docker-compose.yml
    image_keys:
      ansible-ib:
        repository: "ANSIBLE_IMAGE_REPOSITORY"
        tag: "ANSIBLE_IMAGE_TAG"
