version: '2'

services:
  couchdb:
    image: ${COUCHDB_IMAGE_REPOSITORY}:${COUCHDB_IMAGE_TAG}
    user: root
    cap_add:
      - SYS_PTRACE
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=couchdb
    ports:
      - '5984:5984'
      - '4369:4369'
      - '9100:9100'
    volumes:
      - couchdb_data:/opt/couchdb/data
      - ./host_coverage.sh:/opt/bitnami/scripts/host_coverage_script.sh
volumes:
  couchdb_data:
    driver: local
