version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: rapidfort/postgresql-official
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: keycloak/keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: rapidpassword
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: password
        KEYCLOAK_ENABLE_STATISTICS=true
        KEYCLOAK_ENABLE_HEALTH_ENDPOINTS=true
      ports:
        - 8080:8080
      depends_on:
        - postgres
      command: ["start-dev"]