name: prometheus-operator-ib
official_name: Prometheus Operator Iron Bank
official_website: https://prometheus-operator.dev/
source_image_provider: Platform One
source_image_repo: registry1.dso.mil/ironbank/opensource/prometheus-operator/prometheus-operator
source_image_repo_link: https://registry1.dso.mil/harbor/projects/3/repositories/opensource%2Fprometheus-operator%2Fprometheus-operator
source_image_readme: https://repo1.dso.mil/dsop/opensource/prometheus-operator/prometheus-operator/-/blob/development/README.md
rf_docker_link: rapidfort/prometheus-operator-ib
image_workflow_name: prometheus-operator_ironbank
github_location: prometheus-operator/ironbank
report_url: https://us01.rapidfort.com/app/community/imageinfo/registry1.dso.mil%2Fironbank%2Fopensource%2Fprometheus-operator%2Fprometheus-operator
usage_instructions: |
  $ docker run -d --name prometheus-operator rapidfort/prometheus-operator-ib [COMMAND]
what_is_text: |
  The Prometheus Operator provides Kubernetes native deployment and management of Prometheus and related monitoring components.  The purpose of this project is to simplify and automate the configuration of a Prometheus based monitoring stac
  k for Kubernetes clusters.
disclaimer: |
  Trademarks: This software listing is packaged by RapidFort. The respective trademarks mentioned in the offering are owned by the respective companies, and use of them does not imply any affiliation or endorsement.
is_locked: "False"
input_registry:
  registry: registry1.dso.mil
  account: ironbank
repo_sets:
  - opensource/prometheus-operator/prometheus-operator:
      input_base_tag: "v0.75."
      output_repo: prometheus-operator-ib
runtimes:
  - type: docker_compose
    script: dc_coverage.sh
    compose_file: docker-compose.yml
    image_keys:
      prometheus-operator-ib:
        repository: "PROMETHEUS_OPERATOR_IMAGE_REPOSITORY"
        tag: "PROMETHEUS_OPERATOR_IMAGE_TAG"
