apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-cluster-release
  namespace: ci-dev
spec:
  secretName: redis-cluster-release-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - rapidfort
  commonName: redis-cluster-release
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - redis-cluster-release
  # Issuer references are always required.
  issuerRef:
    name: ci-ca-issuer
    kind: Issuer
    group: cert-manager.io
