version: '2'

services:
  python-flask-1:
    image: python:3.6
    volumes:
      - ./configs/sample-server/app:/app
    container_name: python-flask-1
    cap_add:
      - SYS_PTRACE
    networks:
      - haproxy
    expose:
      - "8080"
    command:
      - /bin/bash
      - -c
      - |
        pip install flask==1.0.2
        python3 app/app.py

  python-flask-2:
    image: python:3.6
    volumes:
      - ./configs/sample-server/app:/app
    container_name: python-flask-2
    cap_add:
      - SYS_PTRACE
    networks:
      - haproxy
    expose:
      - "8080"
    command:
      - /bin/bash
      - -c
      - |
        pip install flask==1.0.2
        python3 app/app.py
  
  python-flask-3:
    image: python:3.6
    volumes:
      - ./configs/sample-server/app:/app
    container_name: python-flask-3
    cap_add:
      - SYS_PTRACE
    networks:
      - haproxy
    expose:
      - "8080"
    command:
      - /bin/bash
      - -c
      - |
        pip install flask==1.0.2
        python3 app/app.py
    
  python-flask-4:
    image: python:3.6
    volumes:
      - ./configs/sample-server/app:/app
    container_name: python-flask-4
    cap_add:
      - SYS_PTRACE
    networks:
      - haproxy
    expose:
      - "8080"
    command:
      - /bin/bash
      - -c
      - |
        pip install flask==1.0.2
        python3 app/app.py

  haproxy-1:
    image: ${HAPROXY_IMAGE_REPOSITORY}:${HAPROXY_IMAGE_TAG}
    user: root
    volumes:
      - ./configs/http-mode/haproxy1.cfg:/usr/local/etc/haproxy/haproxy.cfg
    container_name: haproxy-1
    networks:
      - haproxy
    cap_add:
      - SYS_PTRACE
    ports: 
      - '0.0.0.0::80'
    depends_on: 
      - python-flask-1
      - python-flask-2
      - python-flask-3
      - python-flask-4
  
  haproxy-2:
    image: ${HAPROXY_IMAGE_REPOSITORY}:${HAPROXY_IMAGE_TAG}
    user: root
    volumes:
      - ./configs/http-mode/haproxy2.cfg:/usr/local/etc/haproxy/haproxy.cfg
    container_name: haproxy-2
    networks:
      - haproxy
    cap_add:
      - SYS_PTRACE
    ports: 
      - '0.0.0.0::80'
    depends_on: 
      - python-flask-1
      - python-flask-2
      - python-flask-3
      - python-flask-4
  
  haproxy-3:
    image: ${HAPROXY_IMAGE_REPOSITORY}:${HAPROXY_IMAGE_TAG}
    user: root
    volumes:
      - ./configs/http-mode/haproxy3.cfg:/usr/local/etc/haproxy/haproxy.cfg
    container_name: haproxy-3
    networks:
      - haproxy
    cap_add:
      - SYS_PTRACE
    ports: 
      - '0.0.0.0::80'
    depends_on: 
      - python-flask-1
      - python-flask-2
      - python-flask-3
      - python-flask-4
  
  haproxy-quic:
    image: ${HAPROXY_IMAGE_REPOSITORY}:${HAPROXY_IMAGE_TAG}
    user: root
    volumes:
      - ./configs/quic-mode/haproxy-quic.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./certs:/etc/ssl/private
    container_name: haproxy-quic
    networks:
      - haproxy
    cap_add:
      - SYS_PTRACE
    ports: 
      - '0.0.0.0::443'
    depends_on: 
      - python-flask-1
      - python-flask-2
      - python-flask-3
      - python-flask-4

networks:
  haproxy:
    driver: bridge
