version: '2'
services:
  cassandra:
    image: ${CASSANDRA_IMAGE_REPOSITORY}:${CASSANDRA_IMAGE_TAG}
    ports:
      - '0.0.0.0::7000'
      - '0.0.0.0::9042'
    volumes:
      - './tests/test.cql:/opt/test.cql'
      - './logs:/opt/cassandra/logs'
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=200M
    cap_add:
      - SYS_PTRACE
