version: '3.7'

services:
  blackbox-exporter:
    image: ${BB_EXP_IMAGE_REPOSITORY}:${BB_EXP_IMAGE_TAG}
    user: root
    cap_add:
      - SYS_PTRACE
    ports:
      - "9115"
    volumes:
      - configs: /config
    command:
      - '--config.file=/config/blackbox.yml'
    depends_on:
      - grpc_server

  # a gRPC server to test gRPC probing in blackbox-exporter
  grpc-server:
    image: rapidfort/flaskapp
    volumes:
      - ./grpc-server-configs:/app
    ports:
      - "50051"
    working_dir: /app
    command: >
      /bin/sh -c "pip install -r requirements.txt &&
                  python grpc_server.py"
