version: '3'
services:
  elasticsearch:
    image: rapidfort/elasticsearch:8.13.2
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - "discovery.type=single-node"
  
  packetbeat:
    # image: ${PACKETBEAT_IMAGE_REPOSITORY}:${PACKETBEAT_IMAGE_TAG}
    image: kphull/packetbeat-ib:8.13.2-rfstub
    user: root
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    volumes:
      - "./packetbeat.docker.yml:/usr/share/packetbeat/packetbeat.yml:ro"
      # - "./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro"
      # - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      # - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command: -e --strict.perms=false
    depends_on:
      - elasticsearch
