version: '3.8'
services:
  elasticsearch:
    image: registry1.dso.mil/repo1/elastic/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch
    environment:
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - '9200'

  elasticsearch-exporter:
    image: ${ES_EXP_IMAGE_REPOSITORY}:${ES_EXP_IMAGE_TAG}
    container_name: elasticsearch-exporter
    user: root
    cap_add:
      - SYS_PTRACE
    command:
      - '--es.uri=http://elasticsearch:9200'
      - '--es.all'
      - '--es.indices'
      - '--es.indices_settings'
      - '--es.indices_mappings'
      - '--es.shards'
      - '--collector.snapshots'
      - '--es.slm'
      - '--es.data_stream'
    ports:
      - '9114'
    depends_on:
      - elasticsearch
