services:
  zookeeper:
    image: rapidfort/zookeeper-ib:latest
    restart: always
    user: root
    ports:
      - "2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  solr:
    image: ${SOLR_8_IMAGE_REPOSITORY}:${SOLR_8_IMAGE_TAG}
    cap_add:
      - SYS_PTRACE
    environment:
      - SOLR_HEAP=4g 
    ports:
      - "8983"
    volumes:
      - ./coverage.sh:/tmp/coverage.sh
    depends_on:
      - zookeeper
      
volumes:
  solr_data:
    driver: local