version: '3'
services:
  minio-client:
    image: ${MC_IMAGE_REPOSITORY}:${MC_IMAGE_TAG}
    cap_add:
      - SYS_PTRACE
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123; 
      sleep infinity;
      "
    volumes:
      - ./empty.txt:/tmp/empty.txt
    depends_on:
      - minio
    stdin_open: true
    tty: true 
    
  minio:
    image: minio/minio
    command: server /data
    cap_add:
      - SYS_PTRACE
    ports:
      - "9000:9000"
    volumes:
      - data:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123

volumes:
  data:

