version: '2'

services:
  rabbitmq:
    image: ${RABBITMQ_IMAGE_REPOSITORY}:${RABBITMQ_IMAGE_TAG}
    cap_add:
      - SYS_PTRACE
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=bitnami
    ports:
      # AMQP protocol port
      - '5672'
      # HTTP management UI
      - '15672'
