version: '2'
services:
  influxdb:
    image: ${INFLUXDB_OFFICIAL_IMAGE_REPOSITORY}:${INFLUXDB_OFFICIAL_IMAGE_TAG}
    cap_add:
      - SYS_PTRACE    
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb2:rw
    env_file:
      - docker.env.temp
    entrypoint: ["./entrypoint.sh"]
volumes:
  influxdb_data:
    driver: local
