version: '2'

services:
  postgresql:
    image: ${PG_IMAGE_REPOSITORY}:${PG_IMAGE_TAG}
    cap_add:
      - SYS_PTRACE
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
      - ../../common/tests/test.psql:/tmp/test.psql
      - ../../common/tests/common_commands.sh:/tmp/common_commands.sh
      - ../../common/tests/postgres_coverage.sh:/tmp/postgres_coverage.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=my_database
      - PGDATA=/var/lib/postgresql/data

volumes:
  postgresql_data:
    driver: local
