version: "3"

services:
  db:
    image: "registry1.dso.mil/ironbank/opensource/postgres/postgresql:13.6"
    restart: always
    environment:
      POSTGRES_USER: "moodle"
      POSTGRES_PASSWORD: "db-passwd-123"
      POSTGRES_DB: "moodle"
    networks:
      - internal
    volumes:
      - moodle_db:/var/lib/postgresql/data

  moodle:
    image: "registry1.dso.mil/ironbank/opensource/moodle:latest"
    restart: always
    environment:
      MOODLE_DATABASE_HOST: "db"
      MOODLE_DATABASE_NAME: "moodle"
      MOODLE_DATABASE_USER: "moodle"
      MOODLE_DATABASE_PASSWORD: "db-passwd-123"
      MOODLE_DBPORT: 5432
      MOODLE_DB_TYPE: "pgsql"
      MOODLE_SITE_LONG_NAME: "My Moodle Long Name"
      MOODLE_SITE_SHORT_NAME: "My Moodle Short Name"
      MOODLE_URL_SCHEME: "http"
      MOODLE_HOST: "10.18.16.14"
      MOODLE_ADMIN_USERNAME: "admin"
      MOODLE_ADMIN_PASSWORD: "admin"
      MOODLE_ADMIN_EMAIL: "admin@nomail.com"
    networks:
      - internal
    volumes:
      - moodle_www:/var/www/html
      - moodle_data:/var/www/moodledata
    depends_on:
      - db

  webserver:
    image: "registry1.dso.mil/ironbank/opensource/nginx/nginx:1.23.1"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M
    depends_on:
      - moodle
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - moodle_www:/var/www/html
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  moodle_www:
  moodle_data:
  moodle_db: