version: '3'

services:
  minio:
    image: ${MINIO_IMAGE_REPOSITORY}:${MINIO_IMAGE_TAG}
    command: server --console-address ":9001" /data
    cap_add:
      - SYS_PTRACE
    ports:
      - "9090:9000"
      - "9001:9001"
    volumes:
      - data:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  data:
