version: '3'

services:
  yugabyte:
    image: ${YUGABYTE_IMAGE_REPOSITORY}:${YUGABYTE_IMAGE_TAG}
    cap_add:
      - SYS_PTRACE
    ports:
      - "0.0.0.0::7000"
      - "0.0.0.0::9000"
      - "0.0.0.0::5433"
      - "0.0.0.0::15433"
      - "0.0.0.0::9042"
    command:
      - /bin/bash
      - -c
      - |
        ./bin/yugabyted start --daemon=false