name: IB Pipelines Tracker

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions: read-all

jobs:
  pipeline_check:
    name: Image Pipeline Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Pipeline Check
        id: pipeline_check_step
        run: |
          python3 ./scripts/ib_pipelines_check.py | tee ib_tracker_logs.txt
          exit ${PIPESTATUS[0]}
        continue-on-error: true

      - name: Set job status
        if: steps.pipeline_check_step.outcome == 'failure'
        run: |
          echo "Pipeline check failed."
          exit 1

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: pipeline-logs
          path: ib_tracker_logs.txt