name: IB Pipelines Tracker

on:
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

permissions: read-all

jobs:
  pipeline_check:
    name: Image Pipeline Check
    runs-on: ubuntu-latest
    environment: actions-cicd

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Pipeline Status
        run: |
          set -o pipefail
          python3 -u ./scripts/ib_pipelines_check.py