
name: Image Creation PR Run

on:

  pull_request:
    branches:
    - main

  workflow_dispatch:

permissions: read-all

jobs:
  airflow:
    runs-on: ubuntu-latest

    environment: actions-cicd-pr

    steps:

      - name: Import Coverage Tests
        uses: actions/checkout@v4
        with:
          repository: rapidfort/community-images-core
          token: ${{ secrets.COVERAGE_ACCESS_TOKEN }}



      # - name: Check if test required
      #   id: test-required
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     python3 scripts/tests_required.py airflow airflow/airflow/bitnami output.txt
      #     cat output.txt >> $GITHUB_OUTPUT

      # - name: Start minikube

      #   if: ${{ github.event_name == 'pull_request' && steps.test-required.outputs.TEST_REQUIRED == 'yes' }}

      #   with:
      #     memory: 6g
      #   uses: medyagh/setup-minikube@master
      # - name: Check k8s cluster !

      #   if: ${{ github.event_name == 'pull_request' && steps.test-required.outputs.TEST_REQUIRED == 'yes' }}

      #   run: kubectl get pods -A
      - name: Setup ubuntu
        env:
          RF_ACCESS_ID: ${{ secrets.RF_ACCESS_ID }}
          RF_SECRET_ACCESS_KEY: ${{ secrets.RF_SECRET_ACCESS_KEY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          RF_PLATFORM_HOST: ${{ secrets.RF_PLATFORM_HOST }}
          RF_APP_HOST: ${{ secrets.RF_APP_HOST }}

        if: ${{ github.event_name == 'pull_request' && steps.test-required.outputs.TEST_REQUIRED == 'yes' }}

        run: ./scripts/setup.sh

      - name: Set RF CLI Path
        run: |
          ls
          pwd
          echo "/home/runner/work/community-images/community-images" >> $GITHUB_PATH


      - name: Create images for testing PR
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          RAPIDFORT_ACCOUNT: ${{ secrets.RAPIDFORT_ACCOUNT }}
          IB_DOCKER_USERNAME: ${{ secrets.IB_DOCKER_USERNAME }}
          IB_DOCKER_PASSWORD: ${{ secrets.IB_DOCKER_PASSWORD }}
          RF_ACCESS_TOKEN: ${{ secrets.RF_ACCESS_TOKEN }}
        run: |
          docker pull ubuntu:latest
          rfstub ubuntu:latest