name: InfluxDB™ Run

on:
  schedule:
  - cron: '0 * * * *'

  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    environment: actions-cicd
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: Start minikube
        with:
          memory: 4g
        uses: medyagh/setup-minikube@master
      - name: Check k8s cluster !
        run: kubectl get pods -A
      - name: Setup ubuntu
        env:
          RF_ACCESS_ID: ${{ secrets.RF_ACCESS_ID }}
          RF_SECRET_ACCESS_KEY: ${{ secrets.RF_SECRET_ACCESS_KEY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./scripts/setup.sh
      - name: Create images and publish to dockerhub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          IB_DOCKER_USERNAME: ${{ secrets.IB_DOCKER_USERNAME }}
          IB_DOCKER_PASSWORD: ${{ secrets.IB_DOCKER_PASSWORD }}
          PULL_COUNTER_MAGIC_TOKEN: ${{ secrets.PULL_COUNTER_MAGIC_TOKEN }}
        if: github.event_name != 'pull_request'
        run: python3 community_images/common/orchestrator/main.py hourly_run influxdb/bitnami --publish
      - name: Create images for testing PR
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          IB_DOCKER_USERNAME: ${{ secrets.IB_DOCKER_USERNAME }}
          IB_DOCKER_PASSWORD: ${{ secrets.IB_DOCKER_PASSWORD }}
          PULL_COUNTER_MAGIC_TOKEN: ${{ secrets.PULL_COUNTER_MAGIC_TOKEN }}
        if: github.event_name == 'pull_request'
        run: python3 community_images/common/orchestrator/main.py hourly_run influxdb/bitnami
      - name: Report pulls
        env:
          PULL_COUNTER_MAGIC_TOKEN: ${{ secrets.PULL_COUNTER_MAGIC_TOKEN }}
        run: |
          curl -X POST \
           -H "Accept: application/json" \
           -H "Authorization: Bearer ${PULL_COUNTER_MAGIC_TOKEN}" \
           -d '{ "rapidfort/influxdb": 1 }' \
           https://data-receiver.rapidfort.com/counts/internal_image_pulls
