# This is a basic workflow to help you get started with Actions

name: Plenum Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  schedule:
  - cron: '0 0 * * *'
  - cron: '0 12 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    environment: actions-cicd

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: sh scripts/run.sh

      # Clean dangling images
      - name: Clean up dangling images
        run: docker image prune -a -f

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: rapidfort/postgresql
          readme-filepath: ./community_images/postgresql/bitnami/README.md
          short-description: Rapidfort image for bitnami/postgresql

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: rapidfort/redis
          readme-filepath: ./community_images/redis/bitnami/README.md
          short-description: Rapidfort image for bitnami/redis

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: rapidfort/redis-cluster
          readme-filepath: ./community_images/redis-cluster/bitnami/README.md
          short-description: Rapidfort image for bitnami/redis-cluster

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: rapidfort/transformers-pytorch-cpu
          readme-filepath: ./community_images/transformers-pytorch-cpu/huggingface/README.md
          short-description: Rapidfort image for huggingface/transformers-pytorch-cpu

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: rapidfort/yugabyte
          readme-filepath: ./community_images/yugabyte/yugabytedb/README.md
          short-description: Rapidfort image for yugabyte/yugabytedb
