name: MongoDB perfomance test Build

on:
  schedule:
  - cron: '0 0 * * 7'

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment: actions-cicd

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build docker image
        run: ./community_images/mongodb/bitnami/perf_test/build_docker.sh
