name: MongoDB Functional Test

on:
  schedule:
  - cron: '0 */4 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Check k8s cluster !
        run: kubectl get pods -A
      - name: Setup ubuntu
        run: ./scripts/setup.sh --functional yes
      - name: Run functional test
        run: sh community_images/mongodb/bitnami/functional_test.sh
