name: PostgreSQL Run

on:
  schedule:
  - cron: '0 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: actions-cicd
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Check k8s cluster !
        run: kubectl get pods -A
      - name: Setup ubuntu
        env:
          RF_USERNAME: ${{ secrets.RF_USERNAME }}
          RF_PASSWORD: ${{ secrets.RF_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./scripts/setup.sh
      - name: Create images and publish to dockerhub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./community_images/postgresql/bitnami/run.sh yes
      - name: Run functional test
        run: ./community_images/postgresql/bitnami/functional_test.sh

