name: Pull Request Builder

on:
  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment: actions-cicd

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run PRB parallel executor tests
        run: ./scripts/prb_executor.sh
