name: Review Dog
on: [pull_request]

permissions: read-all

jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          path: "." # Optional.
          pattern: "*.sh" # Optional.
          exclude: | 
            ./.git/*
            ./community_images/shellcheck/ironbank/scripts/*
          check_all_files_with_shebangs: "false" # Optional.
          fail_on_error: true