name: Yugabyte Build

on:
  pull_request:
    branches:
    - main
    paths:
    - 'community_images/common/**'
    - 'community_images/yugabyte/yugabytedb/**'
  push:
    branches: [ main ]
    paths:
    - 'community_images/common/**'
    - 'community_images/yugabyte/yugabytedb/**'
  schedule:
  - cron: '0 0 * * *'
  - cron: '0 12 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment: actions-cicd

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs script for the test
      - name: Run a multi-line script
        run: sh community_images/yugabyte/yugabytedb/run.sh

      # Clean dangling images
      - name: Clean up dangling images
        run: docker image prune -a -f

      # Update readme to dockerhub
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: rapidfort/yugabyte
          readme-filepath: ./community_images/yugabyte/yugabytedb/README.md
          short-description: Rapidfort image for yugabyte/yugabytedb
