version: '2'

services:
  apache:
    image: ${APACHE_OFFICIAL_IMAGE_REPOSITORY}:${APACHE_OFFICIAL_IMAGE_TAG}
    user: root
    volumes:
      - ./modules_list:/usr/local/apache2/modules_list:ro
      - ./coverage_script.sh:/usr/local/apache2/coverage_script.sh
    cap_add:
      - SYS_PTRACE    
    ports:
      - '0.0.0.0::8080'
      - '0.0.0.0::8443'
