version: '2'

services:
  apache:
    image: ${APACHE_OFFICIAL_IMAGE_REPOSITORY}:${APACHE_OFFICIAL_IMAGE_TAG}
    user: root
    volumes:
      - ./configs/index.html:/usr/local/apache2/htdocs/index.html
      - ./configs/server-configs/httpd1.conf:/usr/local/apache2/conf/httpd.conf
      - ./certs/server.crt:/usr/local/apache2/conf/server.crt
      - ./certs/server.key:/usr/local/apache2/conf/server.key
    cap_add:
      - SYS_PTRACE    
    ports:
      - "0.0.0.0::80"
      - "0.0.0.0::443"  
  apache-prefork-mpm:
    image: ${APACHE_OFFICIAL_IMAGE_REPOSITORY}:${APACHE_OFFICIAL_IMAGE_TAG}
    user: root
    volumes:
      - ./configs/index.html:/usr/local/apache2/htdocs/index.html
      - ./configs/server-configs/httpd2.conf:/usr/local/apache2/conf/httpd.conf
    cap_add:
      - SYS_PTRACE    
    ports:
      - "0.0.0.0::80"
      - "0.0.0.0::443"
  apache-worker-mpm:
    image: ${APACHE_OFFICIAL_IMAGE_REPOSITORY}:${APACHE_OFFICIAL_IMAGE_TAG}
    user: root
    volumes:
      - ./configs/index.html:/usr/local/apache2/htdocs/index.html
      - ./configs/server-configs/httpd3.conf:/usr/local/apache2/conf/httpd.conf
    cap_add:
      - SYS_PTRACE    
    ports:
      - "0.0.0.0::80"
      - "0.0.0.0::443"
