version: '2'

services:
  debian-ssh:
    image: debian:12.5
    volumes:
      - "./debian-add-ssh.sh:/root/debian-add-ssh.sh"
    command:
      - "/root/debian-add-ssh.sh"
  
  gitlab:
    image: gitlab/gitlab-ee:latest
    hostname: localhost:61780
    ports:
      - "61743:443"
      - "61780:61780"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: 2g

  gitlab-runner:
    image: ${RUNNER_IMAGE_REPOSITORY}:${RUNNER_IMAGE_TAG}
    cap_add:
      - SYS_PTRACE
    user: root
    volumes:
      - ./id_rsa:/root/id_rsa
  
